Refactoring rdkit.Chem.SATIS
rdkit/rdkit pull request #1329
Opened 2017-02-21 20:23 UTC by gedeck

Major rewrite of the code. It's probably best to look at the new code and not on the changes.

2017-02-24 08:00 UTC, greglandrum requested changes
A couple small changes requested.
Thanks for doing the complete rewrite and simplifying the code so much.

2017-02-24 08:00 UTC, greglandrum commented on rdkit/Chem/SATIS.py
Doesn't show up here in the diff, but you might as well remove the `$Id$` line here and update the copyright.

2017-03-07 01:26 UTC, gedeck commented on rdkit/Chem/SATIS.py
Done

2017-03-07 01:28 UTC, gedeck commented
Requested changes implemented

2017-03-07 04:09 UTC, greglandrum approved these changes

2017-03-07 04:10 UTC, merged