Make MetalDisconnector more robust against metallorganics
rdkit/rdkit pull request #3465
Opened 2020-10-04 21:01 UTC by ptosco

I have experienced a very large number of failures when running the `MetalDisconnector` on ligands taken from LigandExpo (http://ligand-expo.rcsb.org/dictionaries/Components-smiles-stereo-oe.smi).
While these are mostly due to malformed/broken SMILES, the purpose of the `MolStandardizer` is reading in and making the most of imperfect molecules, so I believe making the `MetalDisconnector` more robust is a good thing.

2020-10-11 06:02 UTC, greglandrum requested changes
This is producing radical species in some cases and it doesn't seem like that's correct.

2020-10-11 06:02 UTC, greglandrum commented on Code/GraphMol/MolStandardize/test1.cpp
> +       "CNC(=[S])N(C)CCNc1c2ccccc2nc2ccccc12"},
another radical on S

2020-10-11 06:02 UTC, greglandrum commented on Code/GraphMol/MolStandardize/test1.cpp
> +    TEST_ASSERT(MolToSmiles(static_cast<const ROMol &>(*rwmol)) == pair.second);
Switching to this form is, by the way, how I found the strange radical species mentioned above.

2020-10-11 09:39 UTC, ptosco commented on Code/GraphMol/MolStandardize/test1.cpp
> +    TEST_ASSERT(MolToSmiles(static_cast<const ROMol &>(*rwmol)) == pair.second);
@greglandrum Looking at the (crap) input SMILES, I woould say they are indeed intentional. The P and S are all specified as neutral radical species on input, and therefore we have to stick to the input, which is formally correct, even though obviously wrong:

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>SMILES_in</th>      <th>ROMol_in</th>    </tr>  </thead>  <tbody>    <tr>      <th>53</th>      <td>c1ccc(cc1)[P](c2ccccc2)(c3ccccc3)[Pt+2]4(c5ccccc5C6=CC=CC=[N]64)Cl</td>      <td><img data-content="rdkit/molecule" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAEsCAIAAABi1XKVAAAABmJLR0QA/wD/AP+gvaeTAAAgAElEQVR4nOydd1iUR9fGzxY6CIIIqLQVLFhQUVFRsKwFFWMJliQkaiLGRIkliiYajeZNiMbEbrBEjSWKHUHURUVKBAELNhQXRaWDtKUsW+b7Y5L9iCyPlKcBz+96r/eKO7PP3Ch778yZM2d4CCHg4ODgaA7wmRbAwcHBUV84w+Lg4Gg2cIbFwcHRbOAMi4ODo9nAGRYHB0ezgTMsDg6OZgNnWBwcHM0GzrA4ODiaDZxhcXBwNBs4w+Lg4Gg2cIbFwcHRbOAMi6NOEEJZWVnPnj1jWggHxz8ImRbAwVIqKysnTZpkYmJy9uxZa2vrYcOGeXh4DB06tF+/fjwej2l1HK0UHletgaM2crl88uTJly5dMjU11dHRKSgo0DTZ2Nh4eXl5enp6eXm5uLgwKJKjFcIZFsfbqFSqWbNmnTx50tLSMioqysXFJT09PTIyMjY2Nioq6tWrV5qelpaW7u7uQ4cOFYvFffv25fO5CAMHtXCGxfEfVCqVn5/fX3/9ZWZmdvXq1X79+r3VIT09PTY2Ni4u7vLlyxkZGZrX27RpM3DgQLFYzJkXB3VwhsXx/yCE5s+fv3fv3jZt2kRGRg4YMIC4v8a8rly58uLFC83rJiYm7u7uYrHYw8PD3d1dR0eHWt0crQbOsDj+ASG0cOHCXbt2GRoaRkREeHp6NujtWVlZcXFxkZGRkZGR6enpmteNjY0HDRqEzWvgwIG6urpkC+doRXCGxfEPgYGBGzduNDAwCA8PHzFiRFMepTGv2NjYR48eaV43MjIaPHgw3m0cNmyYnp5ek1VztC44w+IAAFi9evX//vc/XV3dM2fOTJgwgcQnZ2dnx8bG4pXj7du3Nb9vhoaGffv2xQF7zrw46glnWBzw66+/Llu2TCAQHDt2bPr06dQNlJubGx0dTWxeQ4cO1dfXp04DR7OGM6zWzrZt27766iuBQPDnn39+8MEHtI2bl5eXkJCAV441zUsoFLq6uuLdRg8PDwMDA9okcbAfzrBaNX/88cdnn30GAMHBwfPmzXtn/8jIyE6dOnXr1o1cGfn5+fHx8di87ty5o1ar8esa8/Lw8PDy8mrTpg2543I0OzjDar38+eefc+bMQQjt2LHjiy++qM9bOnbsmJWV1b59+4EDB+IVHOkndcrKyhISEvBuY03zWrp06ddff21jY0PiWBzND8TRKjl9+rRQKASAoKCger6lrKxsxowZ1tbWNX9/LC0tp02btm3btpSUFLVaTa7IN2/enD9/funSpQ4ODkKh8PPPPyf3+RzNDm6G1Rq5dOnS5MmT5XL5hg0bVq9e3dC315XsrskXJT3ZPTk5uX///ra2ti9fviTrmRzNEc6w2IJcLtfR0aHhREtkZKSPj09VVdXSpUs3b97cxKdpUq4kEsnz5881r9fMF216sjtCqGPHjtnZ2Q8ePOjRo0cTNXM0XzjDYgX79u178uTJ1q1bbW1tRf+le/fuhoaGZA0UFxc3duzY8vLyRYsWbdu2jazHYurKF8XmhfNFPT09G5fsPmfOnIMHD27cuHH58uXkSeZoZnCGxTwSicTb21soFMrl8tqtAoHA1ta2c+fOnTt3dnJy0vyHkZFRQweKj48fM2ZMWVnZnDlz9u/fT2lZK5wvSmKye0hIyIwZM0aMGHHt2jVqJHM0AzjDYphXr165ubnl5+evX79+xYoVmZmZ6f/y8OHDR48evXz5UqlU1n5j27ZtRdqoa6B79+6NHDnyzZs3fn5+Bw8epLOaQk5OTkxMTBPzRUtKSiwtLQEgPz/f1NSUDt0c7IMzLCZRKBTDhw//+++/R48eHRERIRAItPZ59epV+n9JTU0tLy+v3VlfX18kEvXo0aOmhTk4ODx69GjEiBEFBQVTp049ceIE3h9khOzs7KioqOjo6Bs3bjx+/FjzuqGh4eDBg9euXTts2LC63uvl5RUdHX3q1Klp06bRIpaDdXCGxSSff/55cHCwvb19cnKyhYVFg95bVFRUcyKWnp7+7NmzkpKS2j11dHTUarVKpbK1tZ0/f36XLl1cXFy6du3KoG1haia745SrmJiYoUOH1tU/KCho1apVn3766b59++jUycEeOMNijKNHj3700Uf6+vqxsbFubm6kPFPjYhqePn2qNRVAKBTa2dm9tZzs2rWrsbExKUoaSn5+fnR09MSJEwmiWikpKa6urjY2NpmZmVxd+dYJZ1jMkJKSMnjw4IqKiv3798+dO5eiUV6/fu3l5ZWenu7q6rps2bLMzEypVPrs2TOpVPr69eva//Q8Hq9Tp06dO3devnz5+PHjKVLVFOzt7V++fHn79u2+ffsyrYWDAbhbcxiguLh46tSpFRUV/v7+1LlVXl7emDFj0tPT3d3dJRKJiYlJzdbq6urXr1+/NR179OjRq1evXr16VVFR8eDBgxUrVlCkrdGMGzduz549Fy9e5AyrlcJMgn0rRq1WT5kyBQD69OlTUVFB0Sj5+fk9e/YEAFdX18LCwnq+S6FQSKXSn376CQDs7OyUSiVF8hrN2bNnAcDDw4NpIRzMwBkW3axfvx4AzM3N09PTKRqiuLi4f//+ANC1a9ecnJyGvl2tVjs7OwNAeHg4FfKagkwm09PTEwgEBQUFTGvhYADBunXrmJvetTquXr362Wef8Xi8U6dOvfOKh++///6vv/5KTU3Nzc2trq42NjauT454eXn5hAkT4uPjnZ2do6Ki3jqrXB94PF5lZWVkZKRMJps1a1ZD304purq6N27ckEqlffr06dWrF9NyOGiHacdsRbx8+bJdu3YAsH79+vr0r/2BbNu2rZubm6+vb2BgYHBwsEQikUqlNd9SUVExfPhwALCzs3vx4kWjpebn5+vr6wsEgqY8hCLw+Uc/Pz+mhXAwALdLSBNyuXzYsGGJiYkTJkwIDQ2tT6J5ZGRkamqqZl8vPT1d69kdMzMzfFjHwcEhIiIiJSXF2to6Li6OIOu9Pnz44YfHjh377rvvvv/++6Y8h3RSU1O7d+/erl273Nxc7vbD1gZnWDQxf/78PXv2NC5HVEP9k0V1dXU7der0VppVjx496l8uPTo62svLy8bGJiMjg20XCzo5OUml0vj4eHd3d6a1cNAL01O8VsGRI0cAQF9fPykpifSH5+bmxsbGDho0CAB0dXV79+6Nz9zVRkdHx8nJaezYsV988cWvv/56/vz5yspKgifjfcbTp0+TrrmJLFy4EADWrl3LtBAOuuEMi3Lu3buH68Ps37+fiuer1Wpcl93U1DQxMRG/WFlZKZVKQ0NDg4KC/P39xWKxSCSqfVaxuLiY4Mlbt24FgDFjxlAhuymEh4cDwIABA5gWwkE33JKQWoqKigYMGCCVSufPn//777+T/nyE0Jdffrl7925DQ8NLly4RnBwGALlcjleROC6Wn59/4sQJgv4lJSUdO3asqKh48uQJTnRgCZWVle3atauqqsrKyrKysmJaDgeNMO2YLRm1Wj158mSgMkcUV7MzMDC4du0aFc/HifgrVqyg4uFNwdvbGwAOHTrEtBAOWuEMi0KozhH95ptvAEBXVzcsLIyK5yOEEhISAKBdu3bE0S76weVSZ86cybQQDlrhdoWp4urVq99//z2fzz969KijoyPpz1epVFKpVCAQhISEkHu5fE0GDhzo5uZWUFBw5swZioZoHBMnTgSAy5cva61uyNFS4QyLEl6+fDlz5kyVSvX999+PGzeOiiEyMjJOnDhhbGyMP7rU4e/vDwDBwcGUjtJQHB0du3btWlRUFB8fz7QWDvrgDIt85HL5+++/X1BQMHHiRLxqowKRSOTs7FxSUoJXbdTxwQcftGnTJjo6+sGDB5QO1FBwAZyIiAimhXDQB2dY5LNo0aLExER7e3uqS6fjwDPVn1hjY+OPPvoIAPbu3UvpQA0F//gXL15kWggHjTAdRGtpHD58GAD09fWTk5OpHgtblZubW10dysvL8aUPTeTevXsAYGpqKpPJmv40spDL5SYmJjweDxcj5GgNcDMsMklJSZk/fz4A7Nq1q1+/flQPN2LECGNj49u3b2dlZdVuzc7OtrCwEIvFKpWqiQP17t17yJAhJSUlxHlbNKOrqzty5Ej0r3FztAY4wyKNoqIiXEd0/vz5c+bMoWFEPT294cOHI4QuX75cu9XGxsbW1vbNmzekBLmwEbMt9E7PopiDPXCGRQ4Ioblz50ql0r59+/7222+0jUv8iSUxLD1jxgxLS8tbt24lJyc3/WlkMWHCBB6PJ5FIqqurmdbCQQecYZHDhg0bzp07Z25ufvr0aQMDA9rG1aQjKRSK2q0khqX19PT8/PwAYM+ePU1/Gll06tSpZ8+eZWVlsbGxTGvhoAPOsEjg6tWr69evpy5HlAA7OzsXF5fS0tK///67duvw4cONjY3v3LmjNcjVUBYsWMDj8Y4dO1ZaWtr0p5EFl9zQquAMq6lockTXr19PUY4oMQSfWD09vREjRiCELl261PSBnJycRowYIZPJcLUclsAlN7QqOMNqEjVzRFetWsWIBuJPLLlhaRaG3j08PMzMzHA5Q6a1cFAPs1kVzR1ciMrBwYHBS1yqq6tNTU0BQGv9dXztc5s2baqrq0kZq0OHDgAQFxfX9KeRha+vLwDs3LmTaSEclMPNsBrPkSNH9u3bp6+vf/r06UZXPW46Ojo6o0aNAgCt6z5bW9sePXqUlpbGxcWRMtbs2bOBZZMsLrmh9cAZViO5d+8enTmixNCW3AAA8+fPFwgEJ06cyM/PJ+WBTcfb25vH4129erWyspJpLRzUwhlWY9DkiH7++ef05IgSg9ORIiMjtV6rQ25Y2s7ObuzYsXK5HB9CYgPW1tZ9+/atrKyMjo5mWgsHtXCG1WDUavVHH32Unp4+cODALVu2MC0HAMDGxsbV1bW8vFzrJ3bo0KGmpqYPHjzIyMggZTg8tdy9ezdiTX1tLrmhlcAZVoPZsGHDxYsXzc3Njx8/rqenx7ScfyD4xOro6IjF4rpaG8GECRPs7e2fPXt2/fp1Uh7YdPAs8sKFC0wL4aAWzrAaRnp6+g8//CAQCI4fP05zjigxdCY3CAQCXOudPaF3d3d3CwuL9PT0tLQ0prVwUAhnWA0jPz/fwcHBzc1t9OjRTGv5D4MHD7awsHjy5MmzZ89qt44fPx6HpauqqkgZbt68eTo6OmfPniUlh77pCASCsWPHApdB2tLhDKthWFpapqen379/v6ioiGkt/0EgEGAP1TqNsrGx6dOnT11BrkZgY2Pj4+OjUCgOHjxIygObDpfc0BrgDKthiEQisVhcWVlJvEemdbeOauhMboAaWe9Nr7dVH1JSUsLCwgg6jBs3TiAQREVFyWQyGvRwMAPTmavNj9OnTwNA9+7d1Wp17Va1Wu3v729ubp6fn0+zsLy8PD6fb2BgUF5eXrsV1zPo0qULWcOp1Wp8u2p4eDhZz6yLx48ft2/fXkdH58aNGwTdBgwYAAChoaFU6+FgCm6G1WAmTZrUsWPHx48fx8TE1G7l8XjZ2dlv3rw5cOAAzcIsLS3d3NwqKyujoqJqtw4aNMjCwuLp06dag1yNgMfj4ZNJVIfepVLpqFGj8vLyhg8fPnDgwLq6FRQUZGdnDxo0qFevXpTq4WAQzrAajFAo/PTTT6HuD6pmraRWq2lVRrjuIw5yNY65c+fq6+uHh4eTleFVm9evX48ePTorK2vo0KFnz57V19fX2q24uHjs2LGvX78uKytr27YtRWI4mIfpKV6z5NWrVwKBQFdXNzc3t3arSqVycHAAgCtXrtAsDF/S5+joqLX10KFDAODt7U3iiB988AEArFmzhsRnasjJyenWrRsADBo0qLS0tK5uMpls2LBhAODk5JSVlUWFEg6WwBlWI5k0aRIA/Pzzz1pbf/jhBwCYNm0azapUKlX79u0B4PHjx7VbcZBLX19fa5CrceBtR2tra1KqQdQkLy+vR48eANCnT583b97U1a2iomL48OEAYGdn9/z5c3I1cLANzrAaSXh4OACIRCKVSlW7NTs7W0dHRygU0n8DFS5kvHnzZq2tOAYUFhZG4og9e/YEgFOnTpH4zOLiYjc3NwDo1asXQekeuVyOV8EdO3aUSqUkCuBgJ1wMq5GMGzfO0dExPT09MjKydqu1tfXkyZOVSuUff/xBszDi5AYqkpVIv8u+tLR0zJgxycnJzs7OV65cqat0j0Kh8PX1vXjxYvv27SUSiUgkIksAB3th2jGbMf/73/8AYOrUqVpbsZHZ2toqlUo6Vb1580YoFOrq6moN+uArv+oKcjWO4uJiIyMjHo/35MmTpj+tvLzcy8sLAOzs7LSWJMQolcqZM2cCgJmZGSmXxTZrWHXBLaVwhtV4cnJydHV161r3qdXqLl26ABNpQR4eHgBw9uzZ2k0qlcrKygoAHj16ROKIeNt0+fLlTXyOXC7Hc8BOnTqlp6fX1U2tVuOMClNT08TExCYO2nyRSqVbtmwRi8WGhoaLFi26ePEi04oohzOsJjF9+nQA+P7777W2/vLLLwAwYcIEmlXhkL+/v7/W1o8//hgAfvnll/o/8Pjx48Tf4bdu3QIAGxubpkwnq6ur8a1l7du317ppgFGr1QsWLAAAQ0PD6OjoRg/XTCktLT1z5sy8efM6duyoWScJhUIA0NXV1fot1ZLgDKtJXL16FU8HtH5QCwoK9PX1+Xw+zbtXt2/fxqq05uL/9ddfADBq1Kh6Pu306dM8Hq9fv34KhaKuPiEhITweb+nSpY1UjJBSqZwxYwYAtGvX7sGDBwQ9ly9fDgAGBgbXrl1r9HDNDqlUGhwcPHHixJoVjdq3b+/n5xcSElJUVLRs2TIAEAgEhw4dYloshXCG1VRcXFwA4Pz581pb8Z7dt99+S6cktVqNv37v3btXuxUHuXR0dIqLi9/5qCdPnuAbLrZu3VpXn9TU1DZt2gDAjh07GidYpVJ99NFHeImXlJRE0PObb77BUwlyNzrZSUVFhUQiCQwMxMloGIFA4Obmtnbt2qSkpLe+kIKCgnCH/fv3M6WZajjDaiqbN28GgPHjx2ttxSf4qEhTIgYHlX766SetrUOHDgWAM2fOED9EJpPhTKiZM2fW1aesrAxb9qxZsxonVa1W47MBRkZGMTExBD3Xr1+PP5AhISGNG6tZkJ6eHhwc7Ovra2xsrPGpdu3a+fr6Hjp0iCAlDf3rWTweb8uWLbQJphPOsJpKUVGRoaEhn8+vK0jcp08fAKD5M3bq1CkA8PT01NqK9zfnzZtH/BA8PezatStBljmO4vXq1avRG1V4LWNoaHj9+nWCbrgatUAgOHbsWOMGYjMKhSImJiYwMBBnn2H4fL6b [...]

2020-10-11 10:23 UTC, ptosco commented on Code/GraphMol/MolStandardize/test1.cpp
> +    TEST_ASSERT(MolToSmiles(static_cast<const ROMol &>(*rwmol)) == pair.second);
Also, I am not convinced that turning the input radical SMILES into a `ROMol` and converting it again to SMILES should blow away the radical. Is that the right thing to do?

2020-10-11 10:24 UTC, ptosco commented on Code/GraphMol/MolStandardize/test1.cpp
> +       "c1ccc([P](c2ccccc2)c2ccccc2)cc1"},
See answer above

2020-10-11 10:24 UTC, ptosco commented on Code/GraphMol/MolStandardize/test1.cpp
> +       "[S]=C(Nc1ccccc1)c1ccccn1"},
See answer above

2020-10-11 10:24 UTC, ptosco commented on Code/GraphMol/MolStandardize/test1.cpp
> +       "CNC(=[S])N(C)CCNc1c2ccccc2nc2ccccc12"},
See answer above

2020-10-11 10:43 UTC, ptosco commented on Code/GraphMol/MolStandardize/test1.cpp
> +    TEST_ASSERT(MolToSmiles(static_cast<const ROMol &>(*rwmol)) == pair.second);
Ignore my previous answers - the input species is radical (and obviously broken, though formally correct, but that's another story), but heterolytic breakage of the bond should then leave a radical and a charge, while homolytic should leave a neutral stable species. I'll fix that.

2020-10-11 20:38 UTC, ptosco commented
@greglandrum I fixed the issue with radicals, did a code cleanup and added tests.

2020-10-12 03:27 UTC, greglandrum commented
This is not a failing of this PR per se (since the old code also has this wrong), but dative bonds to the metal aren't being properly handled:
```
In [2]: m = Chem.MolFromSmiles('O->[Fe](<-O)(O)O')

In [3]: from rdkit.Chem.MolStandardize import rdMolStandardize

In [4]: md = rdMolStandardize.MetalDisconnector()
[04:50:40] Initializing MetalDisconnector

In [5]: om = md.Disconnect(m)
[04:50:49] Running MetalDisconnector
[04:50:49] Removed covalent bond between Fe and O
[04:50:49] Removed covalent bond between Fe and O
[04:50:49] Removed covalent bond between Fe and O
[04:50:49] Removed covalent bond between Fe and O

In [6]: Chem.MolToSmiles(om)
Out[6]: '[Fe+4].[OH-].[OH-].[OH-].[OH-]'
```

2020-10-12 03:30 UTC, greglandrum approved these changes

2020-10-12 03:32 UTC, greglandrum commented
@ptosco : LGTM
I'm fine merging this as-is and then filing a bug for the way dative bonds are handled, but if you think there's a quick fix (ideally today since I would like to do the beta of the 2020.09 release), we can hold off until that's in

2020-10-12 07:06 UTC, ptosco commented
@greglandrum I'll try and take a look today. If you haven't heard from me before 5am tomorrow morning, I suggest to merge and file a separate bug.

2020-10-12 20:00 UTC, ptosco commented
@greglandrum This is fixed. i added a couple of tests.
The test I removed is about a completely broken molecule (`[Cu]Cl[Cu]`) which is a chemical nonsense. This test was fortuitously passing before you added `+3`, `+5` and `+7` valences to `Cl`, and got broken afterwards.
Given the starting molecule is a nonsense, I removed the test - I had not even noticed that molecule before.

2020-10-13 02:41 UTC, greglandrum approved these changes
LGTM
Thanks Paolo!

2020-10-13 02:41 UTC, greglandrum commented on Code/GraphMol/MolStandardize/Metal.cpp
> +      int order = (b->getBondType() >= Bond::DATIVEONE &&
That's a nice simple solution.

2020-10-13 02:41 UTC, merged