Fixes a few bugs in the R-group decomposition code
rdkit/rdkit pull request #3497
Opened 2020-10-14 19:53 UTC by ptosco

* Even when setting `RGroupLabels` other than to `AutoDetect`, the MCS would still insist to match R-group labels to dummy atoms causing problems (detailed description of the bug here: https://gist.github.com/ptosco/7b6603f1bf665262c1d6022a2c2fccfa and in the new test cases I have added)
* R groups with no substituents in any of the `Add`ed molecules were listed by `GetRGroupsAsColumns`
* Assignment of R-group labels had bugs connected to how `maxLabel` was being set: some indices were missed (e.g., you would see `R1` and `R3` but no `R2`) and things went seriously wrong when using `DummyLabels`.
* `MDLRGroupLabels` and `DummyLabels` were not exposed to Python
* I have added `RGroupCoreAlignment.None_` (while keeping `RGroupCoreAlignment.None` for backwards compatibility) to address the issue reported by @rvianello in #3346)

2020-10-14 23:55 UTC, bp-kelley commented
@ptosco you beat me to it, I was a working on some similar issues.

The osx builds look real.  And perhaps real annoying.

There is another issue where the output rgroups aren't necessarily in order, i.e. R2...R4...R5 this was a regression from a previous build that apparently I forgot to put regression tests on, I'll work on it after we sort these.

2020-10-15 00:01 UTC, bp-kelley requested changes

2020-10-15 00:01 UTC, bp-kelley commented on Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
> +        .value("None_", RDKit::None)
Let's just do a breaking change here and switch it to NoAlignment both ini C++ and in Python.

I never should have used None in the first place ;)

2020-10-15 00:02 UTC, bp-kelley commented on Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp
> +bool rgdAtomCompare(const MCSAtomCompareParameters &p, const ROMol &mol1,
If the user took the trouble to label R1 let's assume that's what they want as R1.

2020-10-16 22:20 UTC, ptosco commented
@greglandrum I fixed the Mac bug (it was a silly one, but it took me a while to set up the build environment on a macincloud instance - my own Mac has become too old to be useful :(. I also added some more tests to cover the `NoAlignment` case.
@bp-kelley this is good to go for me - it would be great if you had a few minutes to sign it off for merging.
I think it is definitely worth fixing these RGD bugs before release.

2020-10-19 11:43 UTC, bp-kelley commented on Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp
> +bool rgdAtomCompare(const MCSAtomCompareParameters &p, const ROMol &mol1,
@ptosco @greglandrum One remaining issue here.

2020-10-19 11:45 UTC, bp-kelley commented
@ptosco  there was one remaining issue but I may have convinced myself not to worry abut it for now.

2020-10-19 11:46 UTC, merged