Fixes #3511
rdkit/rdkit pull request #3513
Opened 2020-10-20 01:36 UTC by ricrogz

This resolves #3511.

A quick wrapping of the return type of the BCUT2D descriptors into a Python list.
I'd prefer a tuple, but AUTOCORR2D is also returning a list, so I guess it makes sense to follow the same pattern.

2020-10-20 03:51 UTC, greglandrum requested changes
The change makes sense to me (and I don't think it would be terrible to be inconsistent, but more correct, here by returning a tuple) but I think the two other overloads of `BCUT` should be adapted the same way.

2020-10-20 10:57 UTC, ricrogz commented
> The change makes sense to me (and I don't think it would be terrible to be inconsistent, but more correct, here by returning a tuple) but I think the two other overloads of `BCUT` should be adapted the same way.

The other overloads (the ones using `BCUT2D_list`, `BCUT2D_tuple` and `BCUT_atomprops`) return pairs of double, which are converted into tuples because of https://github.com/rdkit/rdkit/blob/b5e23dcd4e563f4ce2598e19ce3f5ea1770f287e/Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp#L1727

2020-10-20 14:20 UTC, bp-kelley commented
I admit what is a bit annoying is that the property pickler should be able to pickle std::vector<double> but something in the conversion between python and C++ is really hiding this.

2020-10-21 02:53 UTC, greglandrum commented
> 
> The other overloads (the ones using `BCUT2D_list`, `BCUT2D_tuple` and `BCUT_atomprops`) return pairs of double, which are already converted into tuples because of
> 

Ah, right. Sorry I forgot that; I was just looking at the return types and assuming that they ended up being some kind of opaque object too. In that case: LGTM and I will merge

2020-10-21 02:56 UTC, greglandrum approved these changes

2020-10-21 02:58 UTC, greglandrum commented
The one thing that is missing here is an explicit test for #3511 
I think simply adding the reproducible @d-b-w provided in the bug report to `testMolDescriptors.py` would be fine (and would ensure that this kind of thing doesn't happen again the next time we add a new descriptor)

2020-10-21 13:00 UTC, ricrogz commented
> The one thing that is missing here is an explicit test for #3511
> I think simply adding the reproducible @d-b-w provided in the bug report to `testMolDescriptors.py` would be fine (and would ensure that this kind of thing doesn't happen again the next time we add a new descriptor)

Easily done :)

2020-10-21 15:31 UTC, greglandrum approved these changes

2020-10-21 15:31 UTC, merged