Update Install.md
rdkit/rdkit pull request #3589
Opened 2020-11-26 17:37 UTC by slchan3

#### Reference Issue

https://sourceforge.net/p/rdkit/mailman/message/37162259/
https://sourceforge.net/p/rdkit/mailman/message/37130755/

#### What does this implement/fix? Explain your changes.

conda install instructions now point to the conda-forge instead of rdkit channel.

#### Any other comments?

I am not sure if the rdkit channel is really going to go for good. But at least it has not been working recently,

2020-11-26 20:26 UTC, greglandrum requested changes

2020-11-26 20:26 UTC, greglandrum commented on Docs/Book/Install.md
> +conda install -c conda-forge rdkit-postgresql
unfortunately there's not yet a conda-forge version of the cartridge, so that needs to remain rdkit.

2020-11-26 20:28 UTC, greglandrum commented
I think the rdkit channel will stay around indefinitely, particularly since it's useful for providing beta/nightly releases, but given that the conda-forge builds are automated and support more python versions, I think it's good to point to them for people who can use them.

2020-11-27 04:40 UTC, greglandrum approved these changes

2020-11-27 04:41 UTC, greglandrum commented
Thanks for the contribution @slchan3 !

2020-11-27 04:41 UTC, merged

2020-11-27 22:32 UTC, slchan3 commented
> Thanks for the contribution @slchan3 !

Oh, thank YOU for providing such a useful package!