Fixes #3821 copy constructor by making the template molecule a shared…
rdkit/rdkit pull request #3822
Opened 2021-02-17 14:08 UTC by bp-kelley

Fixes copy constructor for TautomerQueries

2021-02-17 14:08 UTC, bp-kelley commented
@greglandrum @jones-gareth Here is the proposed fix for #3821

2021-02-18 21:07 UTC, bp-kelley commented
@greglandrum @jones-gareth copy constructor now does a deep copy.  I had to change the const RO_SPTR vector and switched to a unique_ptr for the template molecule.

2021-02-19 00:16 UTC, jones-gareth commented
Looks good to me.

2021-02-19 04:23 UTC, greglandrum requested changes
Minor cleanup suggestions.

2021-02-19 04:23 UTC, greglandrum commented on Code/GraphMol/TautomerQuery/TautomerQuery.cpp
> +      RDKit::SubstructMatch(mol, *d_templateMolecule.get(), templateParams);
I don't think you need the `.get()` here:
```suggestion
      RDKit::SubstructMatch(mol, *d_templateMolecule, templateParams);

```

2021-02-19 04:23 UTC, greglandrum commented on Code/GraphMol/TautomerQuery/TautomerQuery.cpp
> +  return PatternFingerprintMol(*d_templateMolecule.get(), fpSize, nullptr, nullptr,
```suggestion
  return PatternFingerprintMol(*d_templateMolecule, fpSize, nullptr, nullptr,

```

2021-02-19 04:23 UTC, greglandrum commented on Code/GraphMol/TautomerQuery/catch_tests.cpp
> +TEST_CASE("TAUTOMERQUERY_COPY_CONSTRUCTOR") {
I think it's helpful to be able to relate issues directly to the tests for them:
```suggestion
TEST_CASE("github #3821 TAUTOMERQUERY_COPY_CONSTRUCTOR") {
```

2021-02-19 19:32 UTC, bp-kelley commented
@jones-gareth @greglandrum I'll push the changes.  I also had the thought that if I used a shared_ptr instead of a unique_ptr we could have operator= do a shallow copy, as it is, I think it will fail to compile.  If we want this behavior I'll make the change.

2021-02-19 20:27 UTC, greglandrum commented
> @jones-gareth @greglandrum I'll push the changes. I also had the thought that if I used a shared_ptr instead of a unique_ptr we could have operator= do a shallow copy, as it is, I think it will fail to compile. If we want this behavior I'll make the change.

What change is this in reference to?

2021-02-22 14:20 UTC, bp-kelley commented
@greglandrum @jones-gareth  I was wrong operator= will use the copy constructor, I added a test for this so we're good to go.

2021-02-22 14:23 UTC, greglandrum commented
> @greglandrum it's the .get() removal.
> 
> The other piece was if we wanted to support operator= as a shallow copy and the copy constructor as a deep copy. As is operator= won't work with the unique_ptr. So I may make it private.

I still don't get it. I believe that `*d_templateMolecule.get()` is exactly equivalent to `*d_templateMolecule`.

2021-02-22 14:32 UTC, bp-kelley commented
@greglandrum it is, looks like I only pushed the header file changes.

2021-02-22 16:34 UTC, bp-kelley commented
@greglandrum pushed the .cpp changes.

2021-02-23 06:41 UTC, greglandrum approved these changes

2021-02-23 06:41 UTC, merged