Make sure that ResonanceMolSupplier subtructure matches are uniquified consistently
rdkit/rdkit pull request #4274
Opened 2021-06-23 16:23 UTC by ptosco

Today I have built the RDKit with a different compiler on a machine with 40 CPU cores and I had a failure in `testCrambin` (`Code/GraphMol/Wrap/rough_test.py`). Upon investigation this turned out to be caused by the algorithm that only keeps unique substructure matches not being deterministic, and hence liable to returning different matches depending on the substructure match concurrency.
This PR implements a robust solution, which I believe is also more elegant and computationally efficient compared to the one that was in place before.
Now match uniquification always returns the match vector with indices in the minimum sorted order across all the possible permutations. I have adjusted `testCrambin` results accordingly.
I am surprised that the test has not failed before.

2021-07-05 07:05 UTC, ptosco commented
The Ubuntu 16.04 build is failing with a strange linker error in `libxml2`, but I don't think that's related to this PR.

2021-07-09 14:27 UTC, greglandrum requested changes
a couple small changes suggested.
Thanks for tracking this down and fixing it.

2021-07-09 14:27 UTC, greglandrum commented on Code/GraphMol/Substruct/SubstructMatch.cpp
> +    typename std::enable_if<
Is this complication necessary?
It's cute to use language features, but isn't there a simpler way to express this?
(Note, there may not be... I haven't banged my head against the syntax and the reference material in order to figure out what this does yet)

2021-07-09 14:27 UTC, greglandrum commented on Code/GraphMol/Substruct/SubstructMatch.cpp
> +  for (auto it = matchesTmp.begin();
I'm not a fan of this syntax. I think it's clearer to just iterate over the elements of `matchesTmp` using the range iteration syntax and then have a break in the loop for when `matches.size()>=args.params.maxMatches`

2021-07-10 21:46 UTC, ptosco commented
@greglandrum I think I have addressed all of your comments; please let me know if this is not the case. Thanks for reviewing!

2021-07-13 04:52 UTC, greglandrum approved these changes

2021-07-13 04:54 UTC, greglandrum commented
An aside: the force-push seems to have really screwed up github's ability to show the diffs in a useable form.

2021-07-13 04:54 UTC, merged