Github4519
rdkit/rdkit pull request #4726
Opened 2021-11-22 15:35 UTC by DavidACosgrove

#### Reference Issue
Fixed 4519

#### What does this implement/fix? Explain your changes.
This fixes 2 bugs.
The first is the one reported by @rachelnwalker about poor placement of SGroup data in a grid picture.  This turned out to be a consequence of drawMolecules() calling setupDrawMolecule twice for each molecule.
The second was the poor placement of SGroupData due to using TestAlignType::START for Group data.

#### Any other comments?
Sorry it's taken so long to get round to fixing these.  The grid one was a real pain both to track down and fix.

2021-11-24 21:26 UTC, DavidACosgrove commented
The failures are due to one of the test drawings (radicals in a grid) being smaller than previously.  I'll take a look to see if that's reasonable or not.

2021-11-29 14:39 UTC, DavidACosgrove commented
The new drawing of radicals in a grid is scaled slightly larger than the current master, which is consistent with the bug fix so I've updated the expected test values.

2021-12-02 03:47 UTC, greglandrum requested changes
Mostly looks good.
My suggested changes are all small cleanup things.

2021-12-02 03:47 UTC, greglandrum commented on Code/GraphMol/MolDraw2D/DrawText.h
> +  void setFontScale(double new_scale, bool ignore_extremes=false);
```suggestion
  void setFontScale(double new_scale, bool ignoreExtremes=false);
```

2021-12-02 03:47 UTC, greglandrum commented on Code/GraphMol/MolDraw2D/DrawText.cpp
> +
```suggestion
void DrawText::setFontScale(double new_scale, bool ignoreExtremes) {
  font_scale_ = new_scale;
  if (ignoreExtremes) {
    return;
  }

```

2021-12-02 03:47 UTC, greglandrum commented on Code/GraphMol/MolDraw2D/DrawText.cpp
> +
minor change to try and avoid having the API get even more inconsistent in terms of naming

2021-12-02 03:47 UTC, greglandrum commented on Code/GraphMol/MolDraw2D/MolDraw2D.cpp
>                 << atom->getIdx() << endl;
I know this isn't part of your PR, but as long as you're in here, please change this to:
```suggestion
          BOOST_LOG(rdWarningLog) << "Couldn't find good place for note " << note << " for atom "
               << atom->getIdx() << std::endl;
```

2021-12-02 03:47 UTC, greglandrum commented on Code/GraphMol/MolDraw2D/MolDraw2D.cpp
>        cerr << "Couldn't find good place for molecule note " << note << endl;
again, not part of this PR, but:
```suggestion
      BOOST_LOG(rdWarningLog) << "Couldn't find good place for molecule note " << note << std::endl;
```

2021-12-02 03:47 UTC, greglandrum commented on Code/GraphMol/MolDraw2D/MolDraw2D.cpp
>                 << bond->getIdx() << endl;
Again, not part of this PR, but:
```suggestion
          BOOST_LOG(rdWarningLog) << "Couldn't find good place for note " << note << " for bond "
               << bond->getIdx() << std::endl;
```

2021-12-02 13:39 UTC, greglandrum approved these changes

2021-12-02 13:39 UTC, merged