Addresses #4754
rdkit/rdkit pull request #4791
Opened 2021-12-11 18:36 UTC by ptosco

This PR addresses #4754 by adding two `CleanupParameters`:
* `largestFragmentChooserUseAtomCount`: enables/disables atom count as `LargestFragmentChooser` criterion
* `largestFragmentChooserHeavyOnly`: count only heavy atoms
A `LargestFragmentChooser` constructor taking `CleanupParameters` as parameter was added to both C++ and Python, and relevant unit tests.

2021-12-14 08:58 UTC, greglandrum requested changes
suggested naming changes

2021-12-14 08:58 UTC, greglandrum commented on Code/GraphMol/MolStandardize/MolStandardize.h
> +  bool largestFragmentChooserHeavyOnly{
consistent with the above suggestion:
```suggestion
  bool largestFragmentChooserCountHeavyAtomsOnly{
```

2021-12-14 08:58 UTC, greglandrum commented on Code/GraphMol/MolStandardize/MolStandardize.h
> +              //! count as criterion (defaults to true)
maybe:
```suggestion
              //! count as one of the criteria (defaults to true)
```

2021-12-14 08:58 UTC, greglandrum commented on Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
> +                     "count as criterion (defaults to True)")
```suggestion
                     "count as one of the criteria (defaults to True)")
```

2021-12-14 08:58 UTC, greglandrum commented on Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
> +                     "count as criterion (defaults to True)")
BTW: nicely done to capitalize `True` here. :-)

2021-12-14 08:58 UTC, greglandrum commented on Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
> +                         largestFragmentChooserHeavyOnly,
```suggestion
                         largestFragmentChooserCountHeavyAtomsOnly,
```

2021-12-14 12:40 UTC, ptosco commented
@greglandrum Done; I have slightly reworded the comments but still along the lines of your suggestion (i.e., improved clarity).

2021-12-15 03:56 UTC, greglandrum approved these changes

2021-12-15 03:56 UTC, merged