Fix a number of crashing bugs in the python wrappers
rdkit/rdkit pull request #4810
Opened 2021-12-20 04:31 UTC by greglandrum

The function `pythonObjectToVect()` returns, by design, a `nullptr` when it's called with either `None` or an empty sequence.

However, there are a bunch of spots in the code where the results of `pythonObjectToVect()` are de-referenced without being checked.

This fixes all of those.

2021-12-24 21:16 UTC, bp-kelley requested changes
Changes are great, the error message it self could be a little more clear.

2021-12-24 21:16 UTC, bp-kelley commented on Code/GraphMol/MMPA/Wrap/rdMMPA.cpp
> +  if (!v) {
Perhaps bondsToCut must be None or non empty.

2021-12-24 21:16 UTC, bp-kelley commented on Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
> +  if (!locs) {
I find these similar, invalid value is a bit vague.

2021-12-24 21:16 UTC, bp-kelley commented on Code/GraphMol/MolStandardize/Wrap/Validate.cpp
> +    throw_value_error("bad value for validations");
I would keep the verbiage the same for all these errors.

2021-12-25 03:46 UTC, greglandrum commented
> Changes are great, the error message it self could be a little more clear.

Makes sense. Those are now all done.

2021-12-27 21:09 UTC, merged