WIP: MMCIF Parser
rdkit/rdkit pull request #4812
Opened 2021-12-21 00:53 UTC by richardjgowers

#### Reference Issue

Fixes #2054 

Currently a work in progress, just checking I'm in the right direction.

TODO:
 - [ ] multiple models
 - [ ] python hookup
 - [ ] cmake things (see below)
 - [ ] more tests

#### What does this implement/fix? Explain your changes.

Adds a PDBx/mmcif parser exposed as `Mol *m = MMCifFileToMol()`

#### Any other comments?

I've copied across the PDB parser test from 1CRN.  The only part not working is the atom serials - `AtomPDBResidueInfo` assumes these are ints, in the PDBx standard they can be strings.

This is using the [gemmi](https://github.com/project-gemmi/gemmi) library for parsing the cif file, it seemed like the best available option.  I'm assuming that this will require working in this as an optional dependency into the CMake files?

2021-12-21 03:42 UTC, greglandrum requested changes
A first round of suggestions.

2021-12-21 03:42 UTC, greglandrum commented on Code/GraphMol/FileParsers/PDBParser.cpp
> +#define GROUP_PDB 0
Please avoid using `#define` for constants. The preferred approach to this would be:
`constexpr size_t GROUP_PDB=0;`

2021-12-21 03:42 UTC, greglandrum commented on Code/GraphMol/FileParsers/PDBParser.cpp
> +    a = PDBAtomFromSymbol(row[TYPE_SYMBOL].c_str());
```suggestion
    auto a = PDBAtomFromSymbol(row[TYPE_SYMBOL].c_str());
```

2021-12-21 03:42 UTC, greglandrum commented on Code/GraphMol/FileParsers/PDBParser.cpp
> +    AtomPDBResidueInfo* info = new AtomPDBResidueInfo(tmp);
```suggestion
    auto info = new AtomPDBResidueInfo(tmp);
```

2021-12-21 03:42 UTC, greglandrum commented on Code/GraphMol/FileParsers/PDBParser.cpp
> +    tmp = t.has_column(ATOMNAME) ? row[ATOMNAME] : "UNL";
```suggestion
    std::string tmp = t.has_column(ATOMNAME) ? row[ATOMNAME] : "UNL";
```

2021-12-21 03:42 UTC, greglandrum commented on Code/GraphMol/FileParsers/PDBParser.cpp
> +    }
I would simplify this whole thing by allocating the conformer and adding it to the molecule outside the loop over atoms.
And I think that for mmcif it's probably ok to skip the check for 3D and just assume that the molecule is 3D.

2021-12-21 03:42 UTC, greglandrum commented on Code/GraphMol/FileParsers/FileParsers.h
> +RDKIT_FILEPARSERS_EXPORT RWMol *MMCifFileToMol(const std::string &fname,
Based on the docs it looks like the format is `mmCIF`, so this probably should be:
```suggestion
RDKIT_FILEPARSERS_EXPORT RWMol *mmCIFFileToMol(const std::string &fname,
```

2021-12-21 03:48 UTC, greglandrum commented
Hi @richardjgowers : thanks for doing this!

If the format is complex enough that we need to add the external dependency, then it will need to be optional and it would be great if the cmake infrastructure could automatically download the required files. I'd suggest adding something like `RDK_BUILD_MMCIF_SUPPORT` to the main `CMakeLists.txt` file. There are a number of examples of how to automate downloads in the codebase already.

2022-01-04 04:02 UTC, greglandrum commented
@richardjgowers : FWIW it looks like the CI test failures on mac and linux are real
Do you have access to either a mac or a windows machine that you can test on?

2022-01-04 15:46 UTC, bp-kelley commented
@richardjgowers If you don't have access to a Mac, I can do a build and try and find the issue.

2022-01-04 16:18 UTC, bp-kelley commented
The error I'm seeing is a sanitization error, but it doesn't make sense it isn't appearing all the time.


```
[11:09:05] testing reading mmcif files
[11:09:05] Explicit valence for atom # 106 O, 3, is greater than permitted
```

2022-01-04 17:03 UTC, bp-kelley requested changes

2022-01-04 17:03 UTC, bp-kelley commented on Code/GraphMol/FileParsers/PDBParser.cpp
> +      RDGeom::Point3D pos = {0.0, 0.0, 0.0};
You can reduce a bit of boiler plate here I think:
```
try {
   if (name2column[CARTNX] >= 0) 
      pos.x = FileParserUtils::toDouble(tokens[name2column[CARTNX]]);
   if (name2column[CARTNY] >= 0) 
      pos.y = FileParserUtils::toDouble(tokens[name2column[CARTNY]]);
   if (name2column[CARTNZ] >= 0)
      pos.z = FileParserUtils::toDouble(tokens[name2column[CARTNZ]]);
   conf->setAtomPos(a->getIdx(), pos);
} catch (boost::bad_lexical_cast &) {
     std::ostringstream errout;
     errout << "Problem with coordinates for PDB atom #" << a->getIdx();
     throw FileParseException(errout.str());
}
```

2022-01-04 17:04 UTC, bp-kelley commented on Code/GraphMol/FileParsers/PDBParser.cpp
> +    parseMmcifAtoms(ifs, name2column, mol, flavor);
@richardjgowers This is the main error, some systems don't have the default locale as "C" so parsing floats can be busted.

2022-01-04 17:08 UTC, bp-kelley commented
It would be useful if we could also parse monomers, or at least be able to do so in the future.

https://www.ccp4.ac.uk/html/mon_lib.html

I think this would be more useful in the small molecule RDKit space, the chemical component dictionaries are available here as a reference.

https://www.wwpdb.org/data/ccd

2022-01-04 17:09 UTC, bp-kelley commented
@richardjgowers Thanks for the contribution btw!

2022-01-04 21:01 UTC, richardjgowers commented
Thanks for the feedback, I've got a test failure (regression wrt PDB format) about bond order, so I guess that's tomorrow's work.

2022-01-06 17:16 UTC, richardjgowers commented
Hit a bit of a problem with the format here.  My PDBx/mmcif version of 4TNA is coming through the parser with 2 fewer bonds, both of these are related to Mg ions.  The PDB format of 4TNA has CONECT records for the Mg ions, mmcif doesn't seem to have an equivalent for CONECT records (https://mmcif.wwpdb.org/docs/pdb_to_pdbx_correspondences.html#CONECT), and the bond guesser is only getting 2 of 4 of the CONECT records.  I think this is then what is causing the regression difference in bond orders later on...

2023-03-17 10:09 UTC, Augustin-Zidek commented
> Hit a bit of a problem with the format here. My PDBx/mmcif version of 4TNA is coming through the parser with 2 fewer bonds, both of these are related to Mg ions. The PDB format of 4TNA has CONECT records for the Mg ions, mmcif doesn't seem to have an equivalent for CONECT records (https://mmcif.wwpdb.org/docs/pdb_to_pdbx_correspondences.html#CONECT), and the bond guesser is only getting 2 of 4 of the CONECT records. I think this is then what is causing the regression difference in bond orders later on...

mmCIF doesn't store this kind of information as it is stored in the [Chemical Component Dictionary](http://www.wwpdb.org/data/ccd) for all named PDB components. Would obtaining the bond information from there be an option? 

It would be really nice if the mmCIF parser could land in PDB as PDB has many limitations and moreover, new structures with 5-letter residue codes will be distributed only in mmCIF format, see https://www.rcsb.org/news/feature/630fee4cebdf34532a949c34 and https://www.rcsb.org/news/feature/607760112786e73a79c76f9d.

2024-11-19 02:43 UTC, closed without merging