[WIP] cdxml parser
rdkit/rdkit pull request #5273
Opened 2022-05-09 18:44 UTC by bp-kelley

This is the bones for a working CDXML parser.

There are a few things left, cis/trans stereo, grabbing the coordinates and parsing into ChemReactions, making proper query atoms for reactions and others I'm sure.

2022-05-09 18:44 UTC, bp-kelley commented
@greglandrum as promised, here is pass #1

2022-05-09 18:53 UTC, bp-kelley commented on Code/GraphMol/FileParsers/CDXMLParser.cpp
> +                    bool sanitize=false) {
sanitize isn't used in this func

2022-05-09 18:54 UTC, bp-kelley commented on Code/GraphMol/ChemTransforms/catch_tests.cpp
> +        if (std::count(smiles.begin(), smiles.end(), '/') != 2)
read stripped out parens

2022-05-11 18:52 UTC, bp-kelley commented
@greglandrum, might need your eyeballs at some point.

I added proper wedge checking, but I'm doing something wrong with this one:

<img width="159" alt="image" src="https://user-images.githubusercontent.com/9888416/167924257-f0024f56-dadf-48fb-b72a-a10b6cb2ec83.png">

It is generating:  C1CC[C@H]2CCCC[C@@H]2C1
as opposed to the expected: C1CC[C@H]2CCCC[C@H]2C1

I expect the bond ordering may be mucking this up as I'm just using the wedging information not the bond ordering and tetrahedral geometry pieces of the spec.

2022-06-14 18:27 UTC, bp-kelley commented on Code/GraphMol/FileParsers/CDXMLParser.cpp
> +                                  for(auto &attrib : node.second.get_child("<xmlattr>")) {
It's in ChemicalReactions now :)

2022-06-14 18:28 UTC, bp-kelley commented
I think I sorted out the stereo, at least it agrees with the chemdraw smiles exporter...

2022-06-27 04:24 UTC, greglandrum commented
@bp-kelley : could you please update the description of this PR to indicate what the current feature coverage is?

2022-06-27 12:07 UTC, greglandrum requested changes
I haven't looked at the cpp files yet, but since I've already made a bunch of suggestions maybe we can do this one in stages.

@bp-kelley let me know if you'd prefer that I go ahead and review the cpp files at the same time.

2022-06-27 12:07 UTC, greglandrum commented on Code/GraphMol/ChemReactions/catch_tests.cpp
> +  SECTION("CDXML REACTION") {
please move the (very verbose) CDXML data to files instead of embedding it in the tests.

2022-06-27 13:45 UTC, bp-kelley commented on Code/JavaWrappers/ChemReactions.i
>  #include <GraphMol/ChemReactions/ReactionPickler.h>
I'm making a reaction collection here, they are surprisingly difficult to find examples for.

2022-06-27 13:49 UTC, bp-kelley commented on Code/JavaWrappers/ChemReactions.i
>  #include <GraphMol/ChemReactions/ReactionPickler.h>
Ah, this is the JavaWrappers.  When we have a cdxml data collection, I'll add them.

2022-07-21 23:00 UTC, bp-kelley commented on Code/GraphMol/FileParsers/cdxml_parser_catch.cpp
> +//
@greglandrum I think these are all addressed now (except removeHs)

1 What happens with there's a syntax error in the CDXML?
  **A FileParserException is thrown with the error and the line number in the xml file**

2 What happens if there's a chemistry problem, i.e. a structure which cannot be kekulized or with a valence violation?
  **Right now, compounds with errors are skipped unless sanitize==False**

3 What happens if there's a chemistry problem with only one of the compounds in a file?
  **It is skipped if sanitize==False**

4 What happens if the specified file does not exist?
  **RDKit::BadFileException is thrown**

5 Maybe you have this already: test that the parser handle molecules in both kekule and aromatic forms (assuming it's possible to get the aromatic form in Chemdraw)
  **Both are now tested.**

6 Tests for the optional arguments (i.e. removeHs and sanitize)
 **Sanitize is tested, unsure about removeHs, I'll check in the morning.**

CC(C)c1ccccc1

2022-07-22 14:47 UTC, greglandrum requested changes
Pass 2...
I still haven't looked at CDXMLParser.cpp. Will do that after this set of stuff is resolved

2022-07-22 14:47 UTC, greglandrum commented on Code/GraphMol/FileParsers/CDXMLParser.cpp
> +//  All rights reserved.
Detail thing: please run clang-format over this file

2022-07-22 14:47 UTC, greglandrum commented on Code/GraphMol/FileParsers/CDXMLParser.cpp
> +Atom * addquery(Q *qry, std::string symbol, RDKit::RWMol &mol, unsigned int idx) {
you have multiple gratuitous `RDKit::` specfications in here that I don't think are necessary

2022-07-24 06:00 UTC, greglandrum requested changes
I think it's also worth thinking about adding something to the documentation to indicate that the cdxml parser is, due to the complexity of the format and all of the random crap that can be in there, still a work in progress

2022-07-25 18:56 UTC, bp-kelley commented on Code/GraphMol/ChemReactions/CDXMLParser.cpp
> +  std::set<unsigned int> used;
The molecule idx's are using the chemdraw idx, so these can be arbitrarily large and random.   A set makes more sense here I think.

2022-07-25 19:34 UTC, bp-kelley commented on Code/GraphMol/FileParsers/CDXMLParser.cpp
> +                  if (coord.size() == 2) {
No idea.

2022-07-25 19:41 UTC, bp-kelley commented on Code/GraphMol/FileParsers/CDXMLParser.cpp
> +        assert(sz % 2 == 0);
Whups!

2022-07-25 21:38 UTC, bp-kelley commented on Code/JavaWrappers/ChemReactions.i
>  #include <GraphMol/ChemReactions/ReactionPickler.h>
There is exactly one right now :)

2022-07-25 21:44 UTC, bp-kelley commented on Code/GraphMol/FileParsers/CDXMLParser.cpp
> +          atom_id = stoi(attr.second.data());
stoi does throw an exception on failure, that I don't currently catch...

2022-09-10 05:31 UTC, greglandrum commented on Code/GraphMol/Wrap/rdmolfiles.cpp
> +       - sanitize: if True, sanitize the molecules [default True]
Need documentation for the `removeHs` argument too

2022-09-10 13:33 UTC, greglandrum approved these changes
mostly small stuff suggested here
I think this is very close.

2022-09-10 13:33 UTC, greglandrum commented on Code/GraphMol/FileParsers/CDXMLParser.cpp
> +                      molzip(*mol, molzip_params).release());  // std::move?
This can be simply:
```suggestion
                  fused = std::move(molzip(*mol, molzip_params));
```

2022-09-10 13:33 UTC, greglandrum commented on Code/GraphMol/ChemReactions/CDXMLParser.cpp
> +//! Parse a text stream in MDL rxn format into a ChemicalReaction
```suggestion
//! Parse a text stream with CDXML data into a ChemicalReaction
```

2022-09-10 13:33 UTC, greglandrum commented on Code/GraphMol/ChemReactions/CDXMLParser.cpp
> +    // RXN-based reactions do not have implicit properties
```suggestion
    // CDXML-based reactions do not have implicit properties
```

2022-09-10 13:33 UTC, greglandrum commented on Code/GraphMol/ChemReactions/CDXMLParser.cpp
> +  if (!inStream) {
```suggestion
  if (!inStream || inStream.bad()) {
```
The rxn file parser doesn't do this check (it should), but the mol file parser does

2022-09-10 13:34 UTC, greglandrum commented
@bp-kelley : I clicked the wrong button with my PR and said "approve" instead of "suggest changes"
I don't think I can actually change this, but there are some changes I think should be made

2022-09-10 19:14 UTC, bp-kelley commented on Code/GraphMol/FileParsers/CDXMLParser.cpp
> +  auto *qa = new QueryAtom(*atm);
I think I copied this code which had an older idiom.  I'll make the change.

2022-09-13 13:06 UTC, greglandrum approved these changes
LGTM
I think we can go ahead and merge this.

2022-09-26 10:48 UTC, greglandrum commented
@bp-kelley: I fixed the merge conflicts and the CI failure is an artifact, so I think this is ready to merge

2022-09-26 19:39 UTC, bp-kelley commented
Yay!

2022-09-28 03:49 UTC, merged

2022-10-14 12:35 UTC, cdvonbargen commented
@bp-kelley  -- this is great, I've had more than one request to integrate this into the sketcher, many thanks for pointing me to it. I know someone is inevitably going to ask for a cdxml writer and wanted to ask if you and @greglandrum think that's appropriate to want included in the rdkit.

2022-10-14 13:25 UTC, ptosco commented
@cdvonbargen I think it would be a great addition.

2022-10-14 16:35 UTC, greglandrum commented
I'm +1 on (and a lot less nervous about) a writer.