Fix segfault in mol zip
rdkit/rdkit pull request #5338
Opened 2022-05-29 13:45 UTC by bp-kelley

Fixes #5334 

FragmentOnBonds allows multiple links with the same label, everything else does not.  This caused issues when looking at the ordering for chirality.

This fixes both issues.

2022-05-30 04:10 UTC, greglandrum requested changes
some small suggestions

2022-05-30 04:10 UTC, greglandrum commented on Code/GraphMol/ChemTransforms/MolFragmenter.cpp
> +    }
wouldn't this work as:
```suggestion
    CHECK_INVARIANT(params.label == MolzipLabel::FragmentOnBonds || !a->getOwningMol().getBondBetweenAtoms(a->getIdx(), b->getIdx()),
                      "molzip: zipped Bond already exists, perhaps labels are duplicated");
```

2022-05-30 04:10 UTC, greglandrum commented on Code/GraphMol/ChemTransforms/catch_tests.cpp
> +          auto smiles = MolToSmiles(*resa);
do we still need this debug output?

2022-05-30 04:10 UTC, greglandrum commented on Code/GraphMol/ChemTransforms/catch_tests.cpp
> +          std::cout << smiles << std::endl;
do we still need this debug output?

2022-06-01 00:23 UTC, bp-kelley commented on Code/GraphMol/ChemTransforms/catch_tests.cpp
> +          auto smiles = MolToSmiles(*resa);
Nope

2022-06-01 00:26 UTC, bp-kelley commented
@greglandrum should be okay once the tests pass

2022-06-01 03:06 UTC, merged

2022-06-01 03:06 UTC, greglandrum approved these changes
LGTM