Fixes #5324
rdkit/rdkit pull request #5355
Opened 2022-06-07 02:16 UTC by bp-kelley

I believe this fixes the sgroup writing issue.

It appears that the headCrossing and tailCrossing were being filled with proper bond indices from getBondBetweenAtoms, but then looking these up in the bondIndexMap as if they were the index of the bond order when being parsed.   This was causing bad lookups when trying to get the bondType.

2022-06-07 02:16 UTC, bp-kelley commented
@greglandrum hopefully this won't break any tests...

2022-06-07 14:55 UTC, bp-kelley commented on Code/GraphMol/SmilesParse/CXSmilesOps.cpp
> -      bondIndexMap[smilesIdx] = bond->getIdx();
smilesIdx could be > than mol.getNumBonds, probably due to closures.  Fortunately the code is vestigial and unused currently.

2022-06-15 20:26 UTC, bp-kelley commented on Code/GraphMol/ChemReactions/catch_tests.cpp
> +  SECTION("githubXXXX") {
Add  the proper github number :)

2022-06-15 20:35 UTC, bp-kelley commented
@greglandrum just a gentle reminder for this bug fix PR

2022-06-16 14:51 UTC, greglandrum commented
> @greglandrum just a gentle reminder for this bug fix PR

Yep; I’m on it.

2022-06-17 04:43 UTC, greglandrum requested changes
small changes to make the tests more strict

2022-06-17 04:43 UTC, greglandrum commented on Code/GraphMol/ChemReactions/catch_tests.cpp
> +    auto rxnb = ChemicalReactionToV3KRxnBlock(*rxn);
I think it makes sense to include a correctness test here too:
```suggestion
    auto rxnb = ChemicalReactionToV3KRxnBlock(*rxn);
    CHECK(rxnb.find("ATOMS=(1 5) XBONDS=(2 4 5) XBHEAD=(1 4) XBCORR=(2 4 5)")!=std::string::npos);
```

2022-06-17 04:43 UTC, greglandrum commented on Code/GraphMol/ChemReactions/catch_tests.cpp
> +    auto mbk = FileParserUtils::getV3000CTAB(*mol, -1);
Please add a correctness test:
```
```
```suggestion
    auto mbk = FileParserUtils::getV3000CTAB(*mol, -1);
    CHECK(mbk.find("ATOMS=(1 5) XBONDS=(2 4 5) XBHEAD=(1 4) XBCORR=(2 4 5)")!=std::string::npos);
```

2022-06-18 07:06 UTC, greglandrum approved these changes
LGTM

2022-06-18 07:06 UTC, merged