Changing flags if doIsomericSmiles is false
rdkit/rdkit pull request #6225
Opened 2023-03-21 23:00 UTC by HalflingHelper

#### Reference Issue
Fixes #6040 

#### What does this implement/fix? Explain your changes.
Checks the doIsomericSmiles param in `MolToCXSmiles` and changing the flags variable that gets passed to `getCXExtensions`

#### Any other comments?
I wasn't able to find anywhere that it's possible for users to define their own flags variable, but I just wanted to makke sure that there is no concern with overwriting flags.

2023-03-22 16:18 UTC, greglandrum requested changes
Thanks for the contribution @HalflingHelper!
The code change here looks good, but before it can be accepted you need to add a test to `cxsmiles_test.cpp` which demonstrates that the problem is fixed.
This can basically just be a translation of the python code in my original bug report into C++.

2023-03-22 22:57 UTC, HalflingHelper commented
@greglandrum 

Tests should be added, and I got them to pass.

2023-03-23 04:22 UTC, greglandrum approved these changes
LGTM

2023-03-23 04:22 UTC, greglandrum commented
> 
> Tests should be added, and I got them to pass.

Thanks!

2023-03-23 04:22 UTC, merged