Using Chiral Tag instead of CIPCode to ensure preservation of chirality
rdkit/rdkit pull request #6259
Opened 2023-03-30 18:43 UTC by HalflingHelper

#### Reference Issue
Fixed #6237 

#### What does this implement/fix? Explain your changes.
The code provided in the issue now generates the wedge bonds on opposite sides of the ring as requested.
This also satisfies the `FIX:` comment in the lines directly above the change that was made

#### Any other comments?

2023-04-01 05:51 UTC, greglandrum requested changes
Thanks for the PR @HalflingHelper!

I made a suggestion to fix (I think) the implementation.

In order for the PR to be merged, you also need to add a test (at least one) which demonstrates that it actually fixes the bug. For this one the most logical place for that test to live is probably `catch_graphmol.cpp`. You can use the tests which are already there to get a sense of what we normally do for testing, but please let me know if you have any questions.

2023-04-01 05:51 UTC, greglandrum commented on Code/GraphMol/AddHs.cpp
> +              if ((otherAtom->getChiralTag() == Atom::ChiralType::CHI_TETRAHEDRAL_CCW && vol < 0) || (otherAtom->getChiralTag() == Atom::ChiralType::CHI_TETRAHEDRAL_CW && vol > 0)) {
The idea here is right, but the implementation doesn't work in the general case.

There is code above (starting at l363) which uses CIP ranks to order the neighbors. The CW/CCW chiral tags, on the other hand, just use the order of the neighbors in the graph.

What I think you can probably do (not tested) is get rid of that `if` and always execute the code from l383-394.

2023-04-03 06:26 UTC, greglandrum commented
@HalflingHelper : the code changes look good now. Thanks.
The PR still needs one or more tests verifying that bug #6237 is fixed before it can be merged. There's a bit more info about this in my previous comment.

2023-04-04 02:32 UTC, HalflingHelper commented
Do you know what in the tests that I wrote could be causing the `rdkit.rdkit (Ubuntu_x64_py311)` checks to fail? Everything was successful for the previous commit, so I'm not sure exactly what would be causing it.

2023-04-04 02:48 UTC, greglandrum commented
> Do you know what in the tests that I wrote could be causing the `rdkit.rdkit (Ubuntu_x64_py311)` checks to fail? Everything was successful for the previous commit, so I'm not sure exactly what would be causing it.

@HalflingHelper it's a failure in the PandasTools tests which is caused by the update to pandas v2.0. It's definitely not your code, so don't worry about it.

2023-04-12 04:30 UTC, greglandrum commented
> @greglandrum do the tests I wrote look ok or did you have something else in mind? I'm just checking in since this hasn't been merged and I wasn't sure if I need to do anything else.

Sorry I'm slow; I haven't had a chance to look at them yet.

2023-04-14 07:03 UTC, greglandrum approved these changes
LGTM

Thanks for the contribution @HalflingHelper !

2023-04-14 07:03 UTC, merged