Switch to determining atom chiral types from pseudo 3D instead of bond dirs
rdkit/rdkit pull request #6456
Opened 2023-06-10 13:52 UTC by greglandrum

The current RDKit code to determine atomic stereochemistry based on bond wedging and 2D atom positions is a mess of trigonometry and special cases. This PR simplifies things by switching to a scheme which uses pseudo-3D:
Atoms at the end of dashed/wedged bonds are set above/below the plane and the stereo is determined using the usual chiral volume calculation. This is simpler (and likely more efficient, though that doesn't really matter here) and should be more maintainable going forward. I think it will also make it easier to identify situations where stereo is ambiguous.

2023-06-22 03:26 UTC, greglandrum commented
@bp-kelley do you have time to look at this one?

2023-06-22 12:35 UTC, bp-kelley commented
I'll look at it by the weekend.

On Wed, Jun 21, 2023 at 11:27 PM Greg Landrum ***@***.***>
wrote:

> @bp-kelley <https://github.com/bp-kelley> do you have time to look at
> this one?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rdkit/rdkit/pull/6456#issuecomment-1601963122>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACLOFIEXM32VFMWPG7XWV5TXMO3QHANCNFSM6AAAAAAZBWHK3Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-25 21:47 UTC, bp-kelley commented on Code/GraphMol/catch_graphmol.cpp
> +  m1->debugMol(std::cerr);
Do we need debugging any more?

2023-06-25 21:52 UTC, bp-kelley requested changes

2023-06-25 21:52 UTC, bp-kelley commented on Code/GraphMol/testChirality.cpp
> +    m->debugMol(std::cerr);
Remove debugging if not needed.

2023-06-25 21:52 UTC, bp-kelley commented on Code/GraphMol/Chirality.cpp
> +              << "Warning: ambiguous stereochemistry - no volume - at atom "
Perhaps '- no chiral volume -'

2023-06-25 21:52 UTC, bp-kelley commented on Code/GraphMol/Chirality.cpp
> +      if (bondVects[order[1]].z * bondVects[order[0]].z < -1e-4 &&
1e-4 is used a lot, should this be a constant or at least split up between distance, angle and volume for clarity?

2023-06-27 02:52 UTC, greglandrum commented on Code/GraphMol/catch_graphmol.cpp
> +  m1->debugMol(std::cerr);
nope!

2023-06-27 04:03 UTC, greglandrum commented
@bp-kelley those changes are made

2023-07-03 09:15 UTC, greglandrum commented
@bp-kelley ok for me to merge this?

2023-07-03 17:28 UTC, bp-kelley approved these changes

2023-07-03 17:28 UTC, bp-kelley commented
You bet!

2023-07-04 02:48 UTC, merged