unused targetBondLength argument in the CDXML parser's scaleBonds
rdkit/rdkit pull request #6469
Opened 2023-06-19 15:19 UTC by rvianello

#### What does this implement/fix? Explain your changes.
This PR should fix a warning about an unused `targetBondLength` argument in the CDXML parser implementation, that looked like an oversight. It then replaces the literal 1.5 value with a constant as suggested in a recent related PR.

2023-06-21 16:07 UTC, rvianello commented
ah, right, thanks, I wasn't expecting any different behavior and tests passed locally, so I didn't check the results from the CI.

2023-07-01 03:56 UTC, greglandrum requested changes
one very minor suggestion

2023-07-01 03:56 UTC, greglandrum commented on Code/GraphMol/FileParsers/CDXMLParser.cpp
> +const double RDKIT_DEPICT_BONDLENGTH = 1.5;
might as well use a constexpr for this
```suggestion
constexpr double RDKIT_DEPICT_BONDLENGTH = 1.5;
```

2023-07-04 14:54 UTC, greglandrum approved these changes
LGTM

2023-07-04 14:54 UTC, merged