Optionally forward Enhanced Stereo Group ids
rdkit/rdkit pull request #6560
Opened 2023-07-18 14:39 UTC by ricrogz

This implements parsing, storing and optionally forwarding the Enhanced Stereo Group ids on output for multiple formats: CXSMILES, mdl V3000, pickle, mol interchange and cdxml (parsing only).

By default, we reassign the Stereo Group IDs, but we can use the `forwardStereoGroupIds()` function to preserve the Stereo Group IDs on output. Still, it must be noted that some operations (stereo group canonicalization, reactions) can either reset the ids or potentially alter the Stereo Groups, so that the IDs won't be preserved even if `forwardStereoGroupIds()` is used.

Also note that Stereo Group id "0" means that the id is not set, so that one will be assigned on the fly on export.

2023-07-21 15:10 UTC, greglandrum requested changes
Suggested changes are all minor, mostly this looks great.

2023-07-24 12:38 UTC, ricrogz commented on Code/GraphMol/SmilesParse/CXSmilesOps.cpp
> +getIndexeSortedGroups(const std::vector<StereoGroup> &groups,
Sure. Not to mention the typo with the extra "e"!

2023-07-24 12:41 UTC, ricrogz commented on Code/GraphMol/StereoGroup.h
> +RDKIT_GRAPHMOL_EXPORT void forwardStereoGroupIds(ROMol& mol);
I'll add one.

2023-07-24 12:42 UTC, ricrogz commented on Code/GraphMol/SmilesParse/CXSmilesOps.cpp
> +        res << "&" << sgItr->getWriteId() << ":";
No, it doesn't hurt :)

2023-07-27 16:52 UTC, greglandrum reviewed
LGTM

2023-07-27 16:53 UTC, greglandrum approved these changes

2023-07-27 16:53 UTC, merged