Add hasQueryHs
rdkit/rdkit pull request #6702
Opened 2023-09-07 16:33 UTC by bp-kelley

This adds a function hasQueryHs that allows users to see if they need to add explicit Hs to molecules being queried.

There are two ways to run the function

To see if the query mol has query hs (these require explicit hydrogen atoms) use:

```
hasQueryHs(mol) # returns if there are query hs in the molecule
```

To see if we have query Hs that MergeQueryHs will not fix:
```
hasQueryHs(mol, unmergableOnly=True)
```

Note that this doesn't check for mapped or isotopic Hs.

2023-09-07 16:33 UTC, bp-kelley commented
@greglandrum if this seems ok, I'll ensure the other wrappers work.

2023-09-09 05:14 UTC, greglandrum requested changes

2023-09-09 05:14 UTC, greglandrum commented on Code/GraphMol/AddHs.cpp
> +  for (const auto &atom : mol.atoms()) {
`mol.atoms()` returns pointers. No need for the reference here

2023-09-09 05:14 UTC, greglandrum commented on Code/GraphMol/AddHs.cpp
> +      case HydrogenType::NotAHydrogen:
pls add a default too for the case that the enum class changes at some point in the future
```suggestion
      case HydrogenType::NotAHydrogen:
      default:
```

2023-09-09 05:14 UTC, greglandrum commented on Code/GraphMol/AddHs.cpp
> +        if (hasQueryHs(*rsq->getQueryMol(), unmergableOnly)) return true;
```suggestion
        if (hasQueryHs(*rsq->getQueryMol(), unmergableOnly)) {
          return true;
        }
```

2023-09-09 05:14 UTC, greglandrum commented on Code/GraphMol/AddHs.cpp
> +      while (childStack.size()) {
```suggestion
      while (!childStack.empty()) {
```

2023-09-09 05:14 UTC, greglandrum commented on Code/GraphMol/AddHs.cpp
> +        } else if (qry->beginChildren() != qry->endChildren()) {
It doesn't hurt to have it, but I don't think the `if` is actually needed here
```suggestion
        } else {
```

2023-09-09 05:14 UTC, greglandrum commented on Code/GraphMol/MolOps.h
> +//!  to the heavy atoms to which they are bound.
comment is wrong, this doesn't return a copy of the molecule

2023-09-09 05:14 UTC, greglandrum commented on Code/GraphMol/MolOps.h
> +RDKIT_GRAPHMOL_EXPORT bool hasQueryHs(const ROMol &mol, bool unnmergableOnly = false);
I think this would be more useful if you dropped the `unmergableOnly` argument and returned a pair:
(`mergableHs`,`unmergableHs`)

2023-09-09 14:50 UTC, greglandrum commented
I think the changes look good and agree that it's a useful function. Want to go ahead and do the wrappers and fix the conflicts?

2023-09-09 21:40 UTC, bp-kelley commented
@greglandrum python wrappers work, I'll do Java tomorrow.

2023-09-10 04:43 UTC, greglandrum commented
Nice! I will be out until Wednesday afternoon. So I'll take a look at the end of the week

2023-09-15 06:59 UTC, greglandrum approved these changes
LGTM

2023-09-15 06:59 UTC, merged