Bad lasso
rdkit/rdkit pull request #6751
Opened 2023-09-26 07:09 UTC by DavidACosgrove

#### Reference Issue
Fixes 6749

#### What does this implement/fix? Explain your changes.
Separates the lasso lines better.
Trims arcs/circles correctly.

#### Any other comments?
Code from issue now produces this on my Mac.
<img width="584" alt="image" src="https://github.com/rdkit/rdkit/assets/9198870/bf172fab-49ad-4f53-820b-e456b8192507">

2023-09-27 15:13 UTC, greglandrum requested changes
The output looks good, but I have some questions/comments about the implementation

2023-10-01 13:38 UTC, DavidACosgrove commented on Code/GraphMol/MolDraw2D/DrawMolMCHLasso.cpp
> +  int lineWidth = 3;
It does scale in this instance, but I will make that more obvious.  The lines look sensible on 1200x800, 600x300 and 300x200 canvases.

2023-10-01 13:38 UTC, DavidACosgrove commented on Code/GraphMol/MolDraw2D/DrawMolMCHLasso.cpp
> +  double rats[] = {1.0, 1.414, 2, 2.828, 4};
If my maths is correct, this doubles the area of the lasso circles, which seems to make for a reasonable effect.

2023-10-03 13:40 UTC, greglandrum commented
lasso_highlights_7.svg has the following bad line in it:
![image](https://github.com/rdkit/rdkit/assets/540511/70bbb44c-8469-4f2c-9a94-7f5f8cf93cc4)
(the orange line below the H on N15

2023-10-03 13:42 UTC, greglandrum commented
The drawing of the reported problem case (`bad_lasso_1.svg`) now looks quite good, IMO.

2023-10-03 14:24 UTC, DavidACosgrove commented
> lasso_highlights_7.svg has the following bad line in it:
> ![image](https://user-images.githubusercontent.com/540511/272281428-70bbb44c-8469-4f2c-9a94-7f5f8cf93cc4.png)
> (the orange line below the H on N15

Groan. I thought I’d cleared all those. I’ll see what can be done, but it’ll be a few days, probably.

2023-10-13 13:13 UTC, greglandrum approved these changes
LGTM

2023-10-13 13:22 UTC, merged