Improved handling of SP/TB/OH reording in SMILES/SMARTS.
rdkit/rdkit pull request #6777
Opened 2023-10-04 10:57 UTC by johnmay

#### Reference Issue

n/a

#### What does this implement/fix? Explain your changes.

- add a ``getMaxNbors(tag)`` utility function to avoid repeated logic in multiple places
- tweak ``getChiralPermutation()`` for handling implicit/missing ligands (uses -1), allow inverse lookup
- use the tweaked chiral ordering in the reading/writing from SMILES

Change how missing/implicit ligands on SP/TB/OH atoms are treated. This does not change the internal RDKit semantics only the to/from SMILES. The missing functionality was ``getChiralPermutation`` needed to support missing ligands and being able to do the inverse look up.

```
Cl[Co@OH1]Cl Cl-Co-Cl trans
Cl[Co@OH1H4]Cl Cl-Co-Cl trans
Cl[Co@OH1](*)(*)(*)(*)Cl Cl-Co-Cl trans
```

This is also useful for SMARTS matching, i.e. matching a partial substructure in a larger octahedral, but will add that another time.

```
SMILES: O=[N+]([O-])[Co@]([NH3])([NH3])([NH3])([NH3])[N+]([O-])(=O) trans-[Co(NH3)4(NO2)2]
SMARTS: N[Co@OH1]N
```

![](https://www.simolecule.com/cdkdepict/depict/bot/svg?smi=O%3D%5BN%2B%5D(%5BO-%5D)%5BCo%40%5D(%5BNH3%5D)(%5BNH3%5D)(%5BNH3%5D)(%5BNH3%5D)%5BN%2B%5D(%5BO-%5D)(%3DO)%20trans-%5BCo(NH3)4(NO2)2%5D&w=-1&h=-1&abbr=on&hdisp=bridgehead&sma=N%5BCo%40OH1%5DN&zoom=1.3&annotate=none&r=0)

```
SMILES: O=[N+]([O-])[Co@]([NH3])([NH3])([NH3])([NH3])[N+]([O-])(=O) trans-[Co(NH3)4(NO2)2]
SMARTS: N[Co@OH3]N
```

![](https://www.simolecule.com/cdkdepict/depict/bot/svg?smi=O%3D%5BN%2B%5D(%5BO-%5D)%5BCo%40%5D(%5BNH3%5D)(%5BNH3%5D)(%5BNH3%5D)(%5BNH3%5D)%5BN%2B%5D(%5BO-%5D)(%3DO)%20trans-%5BCo(NH3)4(NO2)2%5D&w=-1&h=-1&abbr=on&hdisp=bridgehead&sma=N%5BCo%40OH3%5DN&zoom=1.3&annotate=none&r=0)

There was also a minor oversight in the Canon.cp in that reordering was only done ``if (trueOrder.size() >= 3)`` which is not correct now for non-tetrahedral stereochemistry.

I didn't think with would be case originally (hence I did them first) but these changes are independent of #6730 and #6772.

#### Any other comments?

- I think I got all the test cases but on my M1 Mac I get some segfaults on master so will see what azure says.
- RDKit book examples will need updating (happy to do that too)

2024-10-19 06:58 UTC, johnmay commented
I was waiting on this before updating beam/cdk but will go ahead and do that and they can be incompatible. Rare enough I think that’s ok.

2024-10-19 07:00 UTC, johnmay commented
> I was waiting on this before updating beam/cdk but will go ahead and do that and they can be incompatible. Rare enough I think that’s ok.

I should also add those depictions should have highlights but I rolled it back from the live site waiting on this

2024-10-19 15:16 UTC, greglandrum requested changes
Sorry I lost track of this and never reviewed it.

This mostly looks good to me (though I am mainly relying upon the fact that the tests still pass), with the exception of a few minor formatting/code consistency things.

Also: please run clang-format (using the config file in the root dir) across the files to get the formatting consistent.

2024-10-19 15:16 UTC, greglandrum commented on Code/GraphMol/SmilesParse/SmilesParseOps.cpp
> +{
Please add PRECONDITIONS for the naked pointers.

2024-10-19 15:16 UTC, greglandrum commented on Code/GraphMol/NontetrahedralStereo.cpp
> +
```suggestion
  if (inverse) {
    std::swap(nbrPerm, probePerm);
  }
```

2024-10-19 15:16 UTC, greglandrum commented on Code/GraphMol/NontetrahedralStereo.cpp
> +      if (probe.size() > 6) return 0;
```suggestion
      if (probe.size() > 6) { 
        return 0;
      }
```

2024-10-19 15:16 UTC, greglandrum commented on Code/GraphMol/NontetrahedralStereo.cpp
> +      if (probe.size() > 5) return 0;
```suggestion
      if (probe.size() > 5) { 
        return 0;
      }
```

2024-10-19 15:16 UTC, greglandrum commented on Code/GraphMol/NontetrahedralStereo.cpp
> +      if (probe.size() > 4) return 0;
```suggestion
      if (probe.size() > 4) { 
        return 0;
      }
```

2024-10-19 15:16 UTC, greglandrum commented on Code/GraphMol/NontetrahedralStereo.cpp
> +    case Atom::CHI_ALLENE:
this is aspirational  ;-)

2024-10-19 15:16 UTC, greglandrum commented on Code/GraphMol/Canon.cpp
> +          // in future this show be moved up and simplified, there should not
```suggestion
          // in future this should be moved up and simplified, there should not
```

2024-10-19 20:24 UTC, johnmay commented
Thanks - ok should be good now. I can also rebase if needed but I think the merge will still work without issue (since a local rebase on the current master works without conflict).

Please let me know if anything else needed. I realised I should perhaps give a more explict description to summarise for those who haven't spent decades writing chemistry toolkits.

The crux of all these changes is if in SMILES/SMARTS formats implicit (i.e. virtual/labelled) hydrogens and lone-pairs should be handled differently on stereo atoms. Currently in RDKit missing atoms (e.g. lone-pair on sulfoxide) are treated as though they are at the end of the neighbour list but hydrogens are though they are attached the central atom. 

It makes sense to handle these as equivalent otherwise you need to try and work out if you had a hydrogens or not and sometimes you cannot know or need additional logic/checks (i.e. this fix https://github.com/rdkit/rdkit/pull/6730). This PR along with #6772 makes everything consistent but **does** break backwards compatibility albeit in rare cases.

2024-10-21 02:54 UTC, greglandrum approved these changes
LGTM

2024-10-21 02:55 UTC, merged

2024-10-21 02:55 UTC, greglandrum commented
Thanks @johnmay. And sorry, again, for losing track of this one.
I will take a look at #6722 in the next couple of days

2024-10-21 10:16 UTC, johnmay commented
> Thanks @johnmay. And sorry, again, for losing track of this one. I will take a look at #6722 in the next couple of days

No worries, It was only it got marked as stale so thought useful to bump it up again. 

I'll try and find time to add in the SMARTS matching semantics as well - this is what makes it more important to treat implicit neighbours/hydrogens the same otherwise you tie yourself in knots with something like ``Cl[Co@OH1;H0,H1]Cl``.