Sanitize number of radical electrons in case of invalid value assigned by CXSMILES
rdkit/rdkit pull request #6842
Opened 2023-10-27 02:26 UTC by MarioAndWario

#### Reference Issue
Fixes #6370 

#### What does this implement/fix? Explain your changes.
Number of radical electrons are first assigned by the regular SMILES, and then get overridden by the CXSMILES extension. For example,

```python
Chem.MolFromSmiles('[CH4]').Debug()
#	0 6 C chg: 0  deg: 0 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 0
Chem.MolFromSmiles('[CH4] |^1:0|').Debug()
#	0 6 C chg: 0  deg: 0 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 0 rad: 1
Chem.MolFromSmiles('[CH4] |^2:0|').Debug()
#	0 6 C chg: 0  deg: 0 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 0 rad: 2
```

The radical info from CXSMILES may be invalid and therefore should be sanitized. However, current implementation of `assignRadicals()` within `sanitizeMol()` will do nothing if there are no implicit hydrogens (i.e., the atom has explicit hydrogens). The fix is then to allow such sanitization by removing the condition `if (atom->getNumRadicalElectrons())`.

Unittests are added for a set of CXSMILES:
1. `[XHn] |^m:0|` where X is the element symbol, n = 1, ..., valence, m = 1, ..., 7 denotes the radical type.
2. `[NH4+] |^m:0|` where m = 1, ..., 7 denotes the radical type.

I also fix a minor issue in `calcImplicitValence()` where `d_implicitValence` is not overwritten by the return value.

2023-10-27 23:32 UTC, MarioAndWario commented
1. The test failures in `testMolWrite` and `fileParsersTest1` are caused by incorrect radical type assigned to the 1st C in both `[C]C` and `[CH]`. The correct radical type should be trivalent, while the unittests expect monovalent.
```python
Chem.MolFromSmiles('[C]C').Debug()
# 0 6 C chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0 rad: 3
# 1 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
Chem.MolFromSmiles('[CH]').Debug()
# 0 6 C chg: 0  deg: 0 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0 rad: 3
```
2. The test failure in `testMrvToMol` is caused by the incorrect radical type assigned to B in `[B-]C#N`.
```python
Chem.MolFromSmiles("[B-]C#N").Debug()
# 0 5 B chg: -1  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0 rad: 3
# 1 6 C chg: 0  deg: 2 exp: 4 imp: 0 hyb: 2 arom?: 0 chi: 0
# 2 7 N chg: 0  deg: 1 exp: 3 imp: 0 hyb: 2 arom?: 0 chi: 0
```
Here B should be a trivalent radical center but the `.mrv` [file](https://github.com/rdkit/rdkit/blob/4a69bc3493dd3e9bb9f7a519e306fbcb545f1452/Code/GraphMol/MarvinParse/test_data/mrvValence_value.mrv.expected.mrv#L2) expects a monovalent one.

2024-01-13 05:54 UTC, greglandrum commented
@MarioAndWario I'm very sorry for how long it took for me to review this.

2024-01-13 06:09 UTC, greglandrum requested changes
Generally looks good. I made a couple of small suggestions.

2024-01-13 06:09 UTC, greglandrum commented on Code/GraphMol/test1.cpp
> +void testGithub6370() {
Nice. This is a really comprehensive test

2024-01-13 06:09 UTC, greglandrum commented on Code/GraphMol/FileParsers/test1.cpp
> +    TEST_ASSERT(m->getAtomWithIdx(0)->getNumRadicalElectrons() == 3);
My suggestion would be to add something like the following to the "Backwards Incompatible Changes" section of the release notes:

```
  - The way that the number of radical electrons is calculated for atoms coming from mol blocks has been changed. Systems like a `[CH]` marked as a `DOUBLET` will now have three radical electrons assigned. This is consistent with the value from SMILES.
```

2024-01-17 07:27 UTC, MarioAndWario commented on Code/GraphMol/test1.cpp
> +// #include <boost/log/functions.hpp>
Deleted

2024-01-17 07:28 UTC, MarioAndWario commented on Code/GraphMol/FileParsers/test1.cpp
> +    TEST_ASSERT(m->getAtomWithIdx(0)->getNumRadicalElectrons() == 3);
Added.

2024-01-17 07:28 UTC, MarioAndWario commented on Code/GraphMol/MolOps.cpp
>      // don't have them already and don't have implicit Hs:
Removed

2024-01-17 07:30 UTC, MarioAndWario commented
> @MarioAndWario I'm very sorry for how long it took for me to review this.

No worries! I have applied your suggested changes in the latest commit.

2024-01-23 05:21 UTC, greglandrum approved these changes
LGTM

2024-01-23 05:21 UTC, merged

2024-01-23 05:21 UTC, greglandrum commented
@MarioAndWario thanks for the contribution!