MakeScaffoldGeneric isotope removal
rdkit/rdkit pull request #6855
Opened 2023-10-30 13:55 UTC by dehaenw

#### Reference Issue
Fixes #6836 

#### What does this implement/fix? Explain your changes.
reseting the isotope to 0 for every atom to fix unintended retention of isotope labels during generation of generic scaffolds

2023-10-31 05:20 UTC, greglandrum requested changes
@dehaenw thanks for this!
The changes you have made so far look good, but we also always include tests with each bug fix to ensure that the fix actually works. In this case it would be adding a new test at the bottom of ScaffoldNetwork/catch_tests.cpp (use the existing tests as templates) as well as one at the bottom of rdkit/Chem/Scaffolds/UnitTestMurckoScaffold.py

It would also be great if you could extend this PR to fix the similar problem in MolHash/hashfunctions.cpp:ExtendedMurckoScaffold and add a test for that as well in MolHash/catch_tests.cpp

Please let me know have questions about any of these.

2023-11-06 14:27 UTC, dehaenw commented
apologies for the several commits. was working in a clumsy way fixing the tests. tests should now work, I hope they are formatted ok, I also added an isotope reset in the AnonymousGraph part of MolHash/hashfunctions.cpp

2023-11-06 16:16 UTC, greglandrum requested changes
There's one extra file in the PR that shouldn't be there.
Once that's removed, this is fine.

2023-11-06 16:16 UTC, greglandrum commented on rdkit/Chem/Draw/github4763.svg
I don't think this file is part of this PR

2023-11-06 16:34 UTC, dehaenw commented on rdkit/Chem/Draw/github4763.svg
Ah, whoops! Deleting

2023-11-10 19:25 UTC, greglandrum approved these changes
LGTM
Thanks for the contribution @dehaenw!

2023-11-10 19:26 UTC, merged