Removing stereoatoms requires removing CIS/Trans stereo flags
rdkit/rdkit pull request #6901
Opened 2023-11-12 21:56 UTC by bp-kelley

Fixes #6900 

When we remove stereo atoms from a cis/trans bond we should also remove the CIS/TRANS stereo flags since they require stereo atoms for canonicalization.

This might not be the correct fix for this particular problem since we should want:

"C/C=C/N" to fragment with the  into "*/C=C/N" not 
"*C=CN"

However, because we removethe first bond which affects the stereo atoms in the double bond, this causes the errors down stream.

The correct fix is probably to have a custom removeBond that detects this and handles it correctly by adding the new dummy atoms to the stereo bond.

However this fix preserves the current behavior:

```
mol = MolFromSmiles("N/C=C/C")
frag1 = rdMMPA.FragmentMol(mol)

for a,b in frag1:
    if a: print(Chem.MolToSmiles(a),end=", ")
    else: print(a,end=", " )
    print(Chem.MolToSmiles(b))
```

results in 

```
None, CC=C[*:1].N[*:1]
C(=C[*:2])[*:1], C[*:1].N[*:2]
None, C[*:1].NC=C[*:1]
```

2023-11-15 16:27 UTC, greglandrum requested changes
The changes look reasonable, and I agree that this is the right thing to do, but could you please add a direct test of this in `catch_chirality.cpp`?

2023-11-15 16:29 UTC, greglandrum commented
> The correct fix is probably to have a custom removeBond that detects this and handles it correctly by adding the new dummy atoms to the stereo bond.

Alternatively, we could have the MMPA code not actually remove the atom, but just convert it to a dummy.
That would also help with potentially chirality messes.

2023-11-16 13:40 UTC, bp-kelley commented
@greglandrum I agree that MMPA shouldn't remove the atom, I'll make an issue with a test case for maintaining CIS/Trans.

But I think we need to solve both issues independently.

2023-11-16 14:34 UTC, bp-kelley commented
@greglandrum done and of course I caught a bug with the test :)

2023-11-20 16:39 UTC, bp-kelley commented
@greglandrum anything else we want to do here?

2023-11-21 07:00 UTC, greglandrum approved these changes
LGTM

2023-11-21 07:01 UTC, greglandrum commented
> @greglandrum done and of course I caught a bug with the test :)

yay for writing tests! :-)

2023-11-21 07:01 UTC, merged