Add Atom::hasValenceViolation (Take 2)
rdkit/rdkit pull request #7030
Opened 2024-01-08 18:40 UTC by cdvonbargen

**Reference Issue**

Fixes https://github.com/rdkit/rdkit/issues/6242

**What does this implement/fix? Explain your changes.**

Implementation of Atom::hasValenceViolation which calls out to the calculation of explicit and implicit valences with strict=True -- which require refactoring this code to create two static functions for those calculations.

The function always returns false for dummy atoms, query atoms, and query bonds.

2024-01-14 06:19 UTC, greglandrum requested changes
I still like the idea.

I did a PR against your branch with my suggested changes.

2024-01-16 14:40 UTC, cdvonbargen commented
> I did a PR against your branch with my suggested changes.

Ah, terrific! I'll pull those in!

2024-01-16 14:42 UTC, cdvonbargen commented on Code/GraphMol/Atom.cpp
> +static int calculate_explicit_valence(const Atom &atom, bool strict) {
Oh, I did this to keep the free function out of the public API -- is using an unnamed namespace preferred here? Dan convinced me that marking such functions as static was preferable, but happy to use unnamed namespace.

2024-01-18 04:06 UTC, greglandrum approved these changes
LGTM

2024-01-18 04:06 UTC, merged