Add Double Cubic Lattice Volume (DCLV).
rdkit/rdkit pull request #7234
Opened 2024-03-11 16:18 UTC by RPirie96

Method to compute the solvent accessible surface area and volume, van der Waals volume, compactness and packing density of a protein. Implemented from:  Frank Eisenhaber, Philip Lijnzaad, Patrick Argos, Chris Sander and Michael Scharf, "The Double Cubic Lattice Method: Efficient Approaches to Numerical Integration of Surface Area and Volume and to Dot Surface Contouring of Molecular Assemblies", Journal of Computational Chemistry, Vol. 16, No. 3, pp. 273-284, 1995.

#### Reference Issue

#### What does this implement/fix? Explain your changes.
New method based on a chunk of old code from Roger for calculating surface area and volume from a dot surface. Primarily for proteins, but hopefully a useful addition :)

#### Any other comments?

2024-03-11 18:05 UTC, greglandrum commented
Hi @RPirie96 I haven't looked at the code yet, but it certainly sounds interesting.
I'm curious why you decided to put it in `External` instead of `GraphMol`.
We normalize use `External` for interfacing with code from another project. In this case the library is self-contained, so I think it could be either directly under `GraphMol` or, perhaps, part of `GraphMol/Descriptors`

2024-03-13 10:55 UTC, RPirie96 commented
Hi @greglandrum  sorry that was just me not knowing where to put it! I've moved it across to GraphMol/Descriptors, and the tests now all pass so should be good for review

2024-03-16 15:20 UTC, greglandrum commented
@RPirie96 I just did a PR against your branch with a bunch of suggested changes.

2024-03-17 05:20 UTC, greglandrum commented on Code/GraphMol/Descriptors/DCLV.h
> +#ifndef RDKIT_DCLV_H
I forgot this in my other suggestions, but please add a copyright statement modelled on other RDKit files to this and DCLV.cpp

2024-03-19 05:34 UTC, greglandrum requested changes
@RPirie96 : the only thing this is missing is the copyright statements in DCLV.h and DCLV.cpp

If you can get those added in the next few days, then we can add this to the upcoming 2024.03.1 release, which would be cool. :-)

2024-03-20 10:58 UTC, RPirie96 commented
Hi @greglandrum apologies, I missed the original comment about copyright statements - added now so should be good to go.

2024-03-20 11:39 UTC, greglandrum approved these changes
LGTM

2024-03-20 11:40 UTC, greglandrum commented
Thanks for this contribution @RPirie96. 
I will merge it once the CI builds go through.

2024-03-20 12:35 UTC, merged