RGD highlights as in blog post
rdkit/rdkit pull request #7322
Opened 2024-04-02 19:29 UTC by ptosco

This PR contributes a convenient way to visualize multi-colored R-group highlights on the molecule which undergo R-group decomposition, as showcased in this [blog post](https://greglandrum.github.io/rdkit-blog/posts/2021-08-07-rgd-and-highlighting.html), but requiring only a handful of Python commands and no need for substructure matches on top of what is already accomplished by the RGD algorithm itself. The highlighting functionality can also be accessed from JS, as exemplified in the [`rgd_demo.html` HTML page:](https://[ptosco.github.io/rgd/rgd_demo.html](https://ptosco.github.io/rgd/rgd_demo.html))
A few other JSON settings were also exposed to JS and CFFI, namely to enable assigning chiral types based on mol parity and to convert dummy atoms into queries.

2024-08-21 10:17 UTC, ptosco commented
@greglandrum This PR has been open for several months now with no activity apart from me fixing conflicts from time to time.
I think it would be good to merge it before the 2024.09 release. I have just fixed conflicts. Would you have time to review it? Thanks in advance!

2024-08-21 10:23 UTC, greglandrum commented
yeah, I will take a look. Thanks for the reminder

2024-08-21 10:26 UTC, ptosco commented
@greglandrum I have just noticed that this PR also exposes an additional JSON bool flag (`assignChiralTypesFromMolParity`) which is not strictly related to this PR. I am happy to take it out of this PR into a separate PR to keep things tidier; If you confirm that would also be your preference I'll do that.

2024-08-21 11:53 UTC, greglandrum commented
@ptosco yes, it would be significantly easier to review this if the PR only included "one thing": in this case that would be the changes directly related to the RGD highlighting.

It would be great if formatting changes, code cleanups, the JSON stuff, etc. were in separate PRs (I realize this may be non-trivial with formatting changes, but it would make things simpler)

2024-08-21 12:18 UTC, ptosco commented
@greglandrum OK, I'll do some cleanup and ping you when done.

2024-08-21 12:35 UTC, greglandrum commented
Thanks

2024-08-23 13:25 UTC, ptosco commented
@greglandrum OK, I have extracted the last chunk of code into a separate PR (#7749). Once that one will be merged, this one should have no conflicts and hence be ready to review.

2024-08-31 06:17 UTC, greglandrum commented
@ptosco when I try to review this with either the github interface or in VS Code I still see a bunch of changes unconnected to the RGD work. Can you please take a look at that?

2024-09-01 21:22 UTC, ptosco commented
As far as I can see, only the changes to `RDValue.cpp` and `RDValue.h` were unrelated, and they were still displayed in the web UI because I had not merged with `upstream/master` since #7749 was merged. I have now done that, and it seems to me that this PR is now only about enabling RGD highlights from C++, Python and JS.

2024-09-03 11:19 UTC, ptosco commented
@greglandrum Ah, I think I figured out - I guess you refer to the atom and bon multimap support, which in my head are linked to the RGD group but of course can also be used elsewhere. I will extract them into an individual PR now.

2024-09-03 14:02 UTC, greglandrum commented
@ptosco yeah, it really helps to have the PRs as compact as possible.

2024-09-03 16:05 UTC, ptosco commented
@greglandrum I have extracted the code I mentioned into #7787; I'll fix the conflicts here once #7787 is merged.

2024-09-16 07:03 UTC, greglandrum requested changes
A few small changes suggested

2024-09-16 09:14 UTC, ptosco commented on Code/GraphMol/RGroupDecomposition/RGroupData.cpp
> +bool RGroupData::isMolHydrogen(const ROMol &mol) {
No, because it has become `static`, so `const` does not apply (there is no bound object).

2024-09-16 09:15 UTC, ptosco commented on Code/GraphMol/RGroupDecomposition/RGroupData.h
> +  static bool isMolHydrogen(const ROMol &mol);
No, because they are all `static`, so `const` does not apply (there is no bound object).

2024-09-16 09:50 UTC, ptosco commented on Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
> +        const auto &mol = side_chain.second;
That code does not exist anymore - you suggested to use `[]` destructuring to access pair members, and so I did.

2024-09-16 09:50 UTC, ptosco commented on Code/GraphMol/RGroupDecomposition/RGroupMatch.h
> +                        CHECK_INVARIANT(bond, "bond must not be null");
True, that check is useless. I removed it.

2024-09-16 09:55 UTC, ptosco commented
@greglandrum I think I should have addressed all points.

2024-09-16 14:14 UTC, greglandrum approved these changes
LGTM

2024-09-16 14:14 UTC, merged