Expose replaceAtomWithQueryAtom to Python
rdkit/rdkit pull request #7380
Opened 2024-04-22 12:36 UTC by DavidACosgrove

#### Reference Issue
No issue

#### What does this implement/fix? Explain your changes.
Exposes the QueryOps::replaceAtomWithQueryAtom to Python.  At present it's available in C++ and Java/C# but not Python.

#### Any other comments?
As usual, the Boost::Python has been done by analogy and clueless experimentation.  One day, perhaps I'll understand what I'm doing.

At the same time, fixes a recurring typo on docstrings.

2024-04-23 01:51 UTC, bp-kelley commented on Code/GraphMol/Wrap/Queries.cpp
> +    return QueryOps::replaceAtomWithQueryAtom(static_cast<RWMol *>(&mol), &atom);
Might be useful to make a note that replaceAtomWithQueryAtom copies the atom.  I'm not sure this is actually documented anywhere.

2024-04-23 01:51 UTC, bp-kelley requested changes

2024-04-23 01:51 UTC, bp-kelley commented on Code/GraphMol/Wrap/Queries.cpp
> +with additional query contstraints added.)DOC";
contstraints => constraints

2024-04-23 01:52 UTC, bp-kelley commented on Code/GraphMol/Wrap/Queries.cpp
> +with additional query contstraints added.)DOC";
Thanks for fixing propery -> property btw!

2024-04-30 04:15 UTC, greglandrum requested changes
Two small doc suggestions

2024-04-30 04:15 UTC, greglandrum commented on Code/GraphMol/QueryOps.h
> +// a copy of the given atom.  Returns a pointer to that atom.
```suggestion
// a copy of the given atom.  Returns a pointer to that atom.
// if the atom already has a query, nothing will be changed
```

2024-04-30 04:15 UTC, greglandrum commented on Code/GraphMol/Wrap/Queries.cpp
> +of the old.)DOC";
```suggestion
of the old.
If the atom already has a query, nothing will be changed)DOC";
```

2024-05-07 04:50 UTC, greglandrum approved these changes
LGTM

2024-05-07 04:51 UTC, merged