Numpy 2 Support
rdkit/rdkit pull request #7531
Opened 2024-06-16 18:38 UTC by AnnaBruenisholz

Addresses #7477. Should work with both numpy 1 and 2 now. 
## Boost

Requires the patch https://github.com/boostorg/python/pull/432 
This patch has already been merged into master and hence should be included in the next release of boost.

## Pandas
pandas >= 2.2.2 (https://pandas.pydata.org/pandas-docs/stable/whatsnew/v2.2.2.html) required.

2024-06-18 13:51 UTC, greglandrum commented
I have tested this on my linux box with numpy v2.0 installed from conda and a self-installed version of boost 1.85 with the patch mentioned above applied.
All tests pass and everything looks good.

2024-06-18 13:54 UTC, greglandrum requested changes
A very minor change suggested, otherwise this looks great.

Thanks!

2024-06-18 13:54 UTC, greglandrum commented on Code/GraphMol/Descriptors/test3D.py
wow. I didn't think we still had any of this old python2 files still in the repo.
These could actually be removed in some future cleanup PR

2024-06-18 13:54 UTC, greglandrum commented on Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
> +
This is just a formatting change and does not need to be in this PR.

2024-06-19 05:53 UTC, greglandrum approved these changes
LGTM

2024-06-19 05:54 UTC, greglandrum commented
I am surprised (and VERY happy) that this didn't end up requiring a huge number of changes.

Thanks for the analysis and doing the work @AnnaBruenisholz !

2024-06-19 05:54 UTC, merged

2024-07-01 06:10 UTC, jakirkham commented
Thank you both! 🙏