Fix/kminimization
rdkit/rdkit pull request #7535
Opened 2024-06-17 13:55 UTC by nmaeder

This PR fixes/changes a few different things regarding the ETK Minimization.

### 12, 13 and 14 Distance Constraints

Fixes a bug, where the wrong atom pair indices were stored when constraining bonds, angles and dihedrals.
This led to atom pairs that had more than one distance constraint applied to them during ETK minimization.

Also inhibit adding a 1-3 Distance Constraint for which the central atom would be in an improper torsion contribution.

### Lower SP Linearity Force Constant

Lowering the force Constant for Linear SP Atoms from 100 to 1. The high force constant led to a distortion of bond lengths
when paired with ET terms in cases where the ET terms where only able to pull through an SP center by changing a lot
of bond lenghts in the conformer.

### Fix ETDG Distance Constraints

Fix a bug where when only using ETDG, the distance constraints provided were not enforced.

### Varia

- Some range based for loops introduced where outdated for loops were used.
- Uniquifying `DistGeom::Construct3DForceField` and `DistGeom::ConstructPlain3DForceField` where the code was doing the same (can possibly be refactored to prevent code duplication at some point)
- Add a SP Linearity contribution to `DistGeom::construct3DImproperForceField` to make sure, linarity of SP centers is also checked at the end of the ETKDG workflow.
- Adapt tests.

2024-06-28 15:38 UTC, greglandrum requested changes
I made a few small suggestions here and also did a PR against your branch with a few others that were easier to make as code

(plus I wanted to test them ;-))

2024-07-04 07:51 UTC, nmaeder commented on Code/GraphMol/DistGeomHelpers/catch_tests.cpp
> +TEST_CASE("tracking failure causes"){
I think it is also messed up in the master branch. Running clang-format gives me exactly this, but i can double check.

2024-07-04 07:57 UTC, nmaeder commented on Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
> -  mol->addBond(3, 5, Bond::BondType::SINGLE);
i reverted to the old code.

2024-07-04 08:11 UTC, nmaeder commented on Code/GraphMol/DistGeomHelpers/catch_tests.cpp
> +TEST_CASE("tracking failure causes"){
Seems to be a bug in the vs code clang-format extension, running it from the cli fixes it, but as soon as i format it from within vscode, it gets funky again. Will push a cli formatted version

2024-07-04 08:37 UTC, nmaeder commented
Changed code according to the review

2024-07-08 12:59 UTC, greglandrum commented on Code/GraphMol/DistGeomHelpers/catch_tests.cpp
> +    SECTION("basics"){auto mol = "O=c2cc3CCc1ccc(cc1Br)CCc2c(O)c3=O"_smiles;
this formatting is still screwed up, but it's not the end of the world

2024-07-08 13:17 UTC, greglandrum commented on Code/GraphMol/DistGeomHelpers/catch_tests.cpp
> +TEST_CASE("tracking failure causes"){
I also noticed that I was getting weird formatting. Installing a recent version of clang-format with conda (this gives me v18) and then pointing VS Code at that fixes that.

2024-07-08 13:29 UTC, merged