Fix an out of bounds access in ForwardMolSupplier
rdkit/rdkit pull request #7607
Opened 2024-07-12 19:27 UTC by bp-kelley

An update to the osx toolchain on conga hit this long standing bug,

2024-07-13 03:39 UTC, greglandrum requested changes
Minor changes

2024-07-13 03:39 UTC, greglandrum commented on Code/GraphMol/FileParsers/ForwardSDMolSupplier.cpp
> +          while (stmp.length() != 0 || (tempStr.length() && (tempStr[0] == ' ' ||
Please use .empty() instead of comparing length() with zero

2024-07-13 19:01 UTC, greglandrum commented
@bp-kelley The Mac tests are still (again?) failing

2024-07-15 00:47 UTC, bp-kelley commented
@greglandrum I fixed the remaining errors.  I also switched from string[0] to string.at(0) to help me find the issues.  We can switch this back if you like.

2024-07-15 02:38 UTC, bp-kelley commented
@greglandrum yep, it's fixed

2024-07-15 02:41 UTC, greglandrum approved these changes
LGTM

2024-07-15 02:41 UTC, merged