Adds HasPropWithValue Pickler
rdkit/rdkit pull request #7692
Opened 2024-08-06 00:29 UTC by bp-kelley

Adds the ability to pickle HasPropWithValue queries.

2024-08-06 02:37 UTC, bp-kelley commented
@greglandrum I'm not sure if we need to bump the pickle version, I don't remember if you did that for the HasPropQuery and I forgot to check,

2024-08-06 02:38 UTC, bp-kelley commented on Code/GraphMol/MolPickler.cpp
> +        streamWrite(ss, std::get<0>(v));
I should make a note that it's easier to pickle the double value (tolerance) first.

2024-08-06 02:39 UTC, bp-kelley commented on Code/GraphMol/MolPickler.cpp
> +          // what about bit vect?if (pair.key != "HasPropValueQuery")
Remove comment

2024-08-06 02:41 UTC, bp-kelley commented on Code/GraphMol/SubstructLibrary/catch_tests.cpp
> +#endif
I shouldn't have touched this file...  I'll double check

2024-08-06 04:00 UTC, greglandrum commented
> @greglandrum I'm not sure if we need to bump the pickle version, I don't remember if you did that for the HasPropQuery and I forgot to check,

I bumped it in #7680. Since we haven't done a release since then, I don't think we need to do it again.

2024-08-26 09:00 UTC, greglandrum requested changes
Most of this looks good, but the tests aren't particularly comprehensive.
I did a PR against your branch with more tests

2024-08-26 12:46 UTC, bp-kelley commented
@greglandrum nice!

2024-08-26 14:27 UTC, greglandrum approved these changes
LGTM

2024-08-26 14:27 UTC, merged