New contribs for DG
rdkit/rdkit pull request #7711
Opened 2024-08-13 11:32 UTC by nmaeder

#### What does this implement/fix? Explain your changes.

New type contribs added for Angle, Distance, Inversion and the `CrystalFF` torsion constraints. 
These are added both to the `DistGeomUtils` as well as to the `UFF/AtomTyper` (inversions)
The Corresponding tests in `ForceField` are adapted to use the new Contribs.
A `catch_tests.cpp` is added for the new contribs.

#### Any other comments?

I did not change any of the wrappers, i think this is something we need to discuss on how to achieve optimal performant code.

2024-08-14 13:44 UTC, greglandrum requested changes
Some relatively minor changes requested

2024-08-17 03:50 UTC, greglandrum requested changes
The requested changes here are to use the pattern 
```
std::emplace_back(std::move(uptr));
```
instead of:
```
std::emplace_back(uptr.release());
```
I'm not sure if there's an accepted best practice, but the move, which doesn't require an extra construction of a new unique_ptr, seems like the most efficient approach.

I did a bit of benchmarking just to check and found that using move is a bit faster with either clang++ or g++ on linux while .release is a bit faster with clang++ on the mac.
So there's no obvious win.

2024-08-17 03:50 UTC, greglandrum commented on Code/DistGeom/DistGeomUtils.cpp
> +    ff->contribs().emplace_back(inversionContribs.release());
It's better to use move here:
```suggestion
    ff->contribs().emplace_back(std::move(inversionContribs));
```

2024-08-17 03:50 UTC, greglandrum commented on Code/DistGeom/DistGeomUtils.cpp
> +    ff->contribs().emplace_back(torsionContribs.release());
```suggestion
    ff->contribs().emplace_back(std::move(torsionContribs));
```

2024-08-17 03:50 UTC, greglandrum commented on Code/DistGeom/DistGeomUtils.cpp
> +    ff->contribs().emplace_back(distContribs.release());
```suggestion
    ff->contribs().emplace_back(std::move(distContribs));
```

2024-08-17 03:50 UTC, greglandrum commented on Code/DistGeom/DistGeomUtils.cpp
> +    ff->contribs().emplace_back(angleContribs.release());
```suggestion
    ff->contribs().emplace_back(std::move(angleContribs));
```

2024-08-17 03:50 UTC, greglandrum commented on Code/DistGeom/DistGeomUtils.cpp
> +    ff->contribs().emplace_back(distContribs.release());
```suggestion
    ff->contribs().emplace_back(std::move(distContribs));
```

2024-08-17 03:50 UTC, greglandrum commented on Code/DistGeom/DistGeomUtils.cpp
> +    ff->contribs().emplace_back(distContribs.release());
```suggestion
    ff->contribs().emplace_back(std::move(distContribs));
```

2024-08-17 03:50 UTC, greglandrum commented on Code/DistGeom/DistGeomUtils.cpp
> +    field->contribs().emplace_back(angleContribs.release());
```suggestion
    field->contribs().emplace_back(std::move(angleContribs));
```

2024-08-17 03:50 UTC, greglandrum commented on Code/ForceField/catch_tests.cpp
> +    forceField->contribs().emplace_back(contribs.release());
```suggestion
    forceField->contribs().emplace_back(std::move(contribs));
```

2024-08-17 03:50 UTC, greglandrum commented on Code/ForceField/catch_tests.cpp
> +    forceField->contribs().emplace_back(contribs.release());
```suggestion
    forceField->contribs().emplace_back(std::move(contribs));
```

2024-08-17 03:50 UTC, greglandrum commented on Code/ForceField/catch_tests.cpp
> +    forceField->contribs().emplace_back(contribs.release());
```suggestion
    forceField->contribs().emplace_back(std::move(contribs));
```

2024-08-17 03:50 UTC, greglandrum commented on Code/ForceField/catch_tests.cpp
> +    forceField->contribs().emplace_back(contribs.release());
```suggestion
    forceField->contribs().emplace_back(std::move(contribs));
```

2024-08-20 08:50 UTC, nmaeder commented
i switched everything from 
`forcefield->contribs().emplace_back(contribs.release())`
to:
`forcefield->contribs().push_back(std::move(contribs))`

2024-08-21 04:06 UTC, greglandrum approved these changes
LGTM

2024-08-21 04:06 UTC, merged