Ignore atom map numbers when generating canonical SMILES
rdkit/rdkit pull request #7732
Opened 2024-08-20 10:59 UTC by DavidACosgrove

#### Reference Issue

Relevant to #4830.  Requested by [@laurenreid1](https://github.com/laurenreid1)

#### What does this implement/fix? Explain your changes.
When generating canonical SMILES, the atom maps are temporarily removed so that the atom order is the same as if the atom maps weren't present.

#### Any other comments?

2024-08-23 03:37 UTC, greglandrum requested changes
The idea is useful. I made some suggested clarifications to the docs

2024-08-23 03:37 UTC, greglandrum commented on Code/GraphMol/SmilesParse/SmilesWrite.h
> +                                        when generating canonical SMILES */
The original formulation almost makes it sound like the atom map numbers will not show up in the SMILES
```suggestion
  bool ignoreAtomMapNumbers = false; /**< If true, ignores any atom map numbers
                                        when canonicalizing the molecule */
```

2024-08-23 03:37 UTC, greglandrum commented on Code/GraphMol/SmilesParse/SmilesWrite.h
> +  generating canonical SMILES
```suggestion
  canonicalizing the molecule
```

2024-08-23 03:37 UTC, greglandrum commented on Code/GraphMol/Wrap/rdmolfiles.cpp
> +          "ignore atom map numbers when generating canonical SMILES");
```suggestion
          "ignore atom map numbers when canonicalizing the molecule");
```

2024-08-23 03:37 UTC, greglandrum commented on Code/GraphMol/Wrap/rdmolfiles.cpp
> +      "  generating canonical SMILES \n\
```suggestion
      "  canonicalizing the molecule \n\
```

2024-08-23 09:12 UTC, DavidACosgrove commented
All done.

2024-08-23 15:15 UTC, greglandrum approved these changes
LGTM

2024-08-23 15:15 UTC, merged

2025-08-17 22:19 UTC, KunhuanLiu commented
Hi,
I hope to confirm the intended behavior here. The current code looks to me is that ignoreAtomMapNumbers behaves differently when a "non-canonical" SMILES is generated versus when a canonical SMILES is generated:
```
from rdkit import Chem

def params(canonical, ignore):
    p = Chem.SmilesWriteParams()
    p.canonical = canonical
    p.ignoreAtomMapNumbers = ignore
    return p

mol = Chem.MolFromSmiles("OCC")
for i, atom in enumerate(mol.GetAtoms()):
    atom.SetAtomMapNum(i+1)

# canonical case, always print AtomMapNumbers
print(Chem.MolToSmiles(mol, params(canonical=True, ignore=True)))   # [CH3:3][CH2:2][OH:1]
print(Chem.MolToSmiles(mol, params(canonical=True, ignore=False)))  # [OH:1][CH2:2][CH3:3]

# non-canonical case, ignoreAtomMapNumbers truly sets AtomMapNum to 0
print(Chem.MolToSmiles(mol, params(canonical=False, ignore=True)))  # OCC
print(Chem.MolToSmiles(mol, params(canonical=False, ignore=False))) # [OH:1][CH2:2][CH3:3]
```

While I don't see any issue with this design, it did make me confused initially. I think it is worth documenting in the api.