Update SA score to use FingerprintGenerators
rdkit/rdkit pull request #7795
Opened 2024-09-06 08:25 UTC by UnixJunkie

#### Reference Issue
Fixes https://github.com/rdkit/rdkit/issues/7794

#### What does this implement/fix? Explain your changes.
The SA score is impacted by the new fingerprint interface.

#### Any other comments?
I tested on 1000 lead-like molecules that the new scores are the same as the old scores.

2024-09-11 07:53 UTC, UnixJunkie commented
Maybe, someone lucky enough to attend the rdkit UGM 2024 will be able to push the merge button for this PR.
Thanks!

PS: have fun, lucky you. :-)

2024-09-17 06:05 UTC, greglandrum requested changes
Suggested changes to use the fingerprint generator as they are intended to be used

2024-09-17 06:05 UTC, greglandrum commented on Contrib/SA_Score/sascorer.py
> +mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=4294967295)
You should be using `GetSparseCountFingerprint()` below, in which case you do not need to specify the size for the FP here:
```suggestion
mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=2)
```

2024-09-17 06:05 UTC, greglandrum commented on Contrib/SA_Score/sascorer.py
> +  fp = mfpgen.GetCountFingerprint(m)
```suggestion
  fp = mfpgen.GetSparseCountFingerprint(m)
```

2024-09-17 07:19 UTC, UnixJunkie commented
The proposed changes have been committed, and my regression test is still OK (results unchanged compared to old version). So, I think this PR is ready to be merged.

2024-09-17 10:18 UTC, greglandrum approved these changes
LGTM

2024-09-17 10:19 UTC, merged

2024-09-17 10:19 UTC, greglandrum commented
Thanks @UnixJunkie !