Prevent SIGSEGV in SplitMolByPDBResidues
rdkit/rdkit pull request #7880
Opened 2024-10-01 18:59 UTC by timpalpant

#### Reference Issue
Fixes #5599 

#### What does this implement/fix? Explain your changes.
The `SplitMolByPDB*` functions dereference an `Atom`'s `MonomerInfo*` that may be null if the molecule was not loaded from a PDB. This leads to a `SEGFAULT` in Python.

This change adds a check for non-null `MonomerInfo*` before dereferencing it to avoid this crash.

#### Any other comments?

Added a basic unit test that calls these functions as in #5599

2024-10-01 19:26 UTC, bp-kelley approved these changes

2024-10-02 10:21 UTC, greglandrum commented
The CI build failures are not due to anything in this PR.
Something has changed on the Mac CI machines, they don't seem to have conda installed any more, that is causing the problems. I will look into it.

2024-10-05 05:49 UTC, greglandrum requested changes
Thanks for the contribution!
The code changes look good, but I've made a couple of requests about the tests.

2024-10-05 05:49 UTC, greglandrum commented on Code/GraphMol/Wrap/rough_test.py
> +    assert len(res2mol) == 1
please use `self.assertEqual()`, not a bare assert.

2024-10-05 05:49 UTC, greglandrum commented on Code/GraphMol/Wrap/rough_test.py
> +    assert len(res2mol) == 1
same request here

2024-10-05 09:04 UTC, timpalpant commented
Thanks for reviewing! I've pushed an update to remove the bare asserts

2024-10-10 12:31 UTC, greglandrum approved these changes
LGTM

2024-10-10 12:31 UTC, merged