Optimize Butina Clustering for Performance and Expand API
rdkit/rdkit pull request #7892
Opened 2024-10-03 22:50 UTC by evasnow1992

#### Reference Issue

#### What does this implement/fix? Explain your changes.

- Optimized Butina clustering algorithm using NumPy arrays for improved performance
- Enhanced modularity and overall code readability
- Expanded API to support direct use of NumPy arrays as input
- Added support for nxn input distance matrices

#### Any other comments?

2024-10-03 23:05 UTC, evasnow1992 commented
We've benchmarked the performance of our optimized Butina clustering implementation against the current RDKit implementation. The first figure below shows the times of speed up of clustering 10,000 randomly selected molecules from ZINC15 dataset in SMILES using Morgan fingerprints for distance computation with a distance threshold of 0.7. For our implementation, when using a list of data as input, it consistently achieves ~3x speedup compared to the current RDKit implementation. If allowing using a NumPy nxn distance matrix, the speedup can be as high as 10x and is likely to increase as the number of molecules increases.

We understand that the actual speedup may be affected by data density or the selection of distance threshold. So in the second figure below we show the speedup of our implementation, with the list and NumPy inputs for different numbers of resulting clusters. When using list input, our implementation achieves 1-5x speedup across different data densities. If a NumPy distance matrix is used, the speedup can be as high as 100x for sparse data (large cluster number).

![Picture1](https://github.com/user-attachments/assets/494438cd-2df5-484a-ad01-81c6a892ae56)
![Picture2](https://github.com/user-attachments/assets/dc6d467a-54eb-4a93-9c9b-c347f7a20a50)

2024-10-10 14:21 UTC, greglandrum requested changes
The performance data looks great! Thanks for doing this.

I made a few minor cleanup suggestions.

2024-10-10 14:21 UTC, greglandrum commented on rdkit/ML/Cluster/Butina.py
> +    if not isinstance(data, (list, np.ndarray)):
Any reason to not also support tuples here?

2024-10-10 14:21 UTC, greglandrum commented on rdkit/ML/Cluster/Butina.py
> +    if isinstance(data, list) or isinstance(data, np.ndarray) and data.ndim == 1:
readability suggestion:
```suggestion
    if isinstance(data, list) or (isinstance(data, np.ndarray) and data.ndim == 1):
```

2024-10-10 14:21 UTC, greglandrum commented on rdkit/ML/Cluster/Butina.py
> +      raise ValueError(f"Unsupported type for data, {type(data)}")
If the argument type is wrong, shouldn't this be a `TypeError`?

2024-10-10 14:21 UTC, greglandrum commented on rdkit/ML/Cluster/UnitTestButina.py
>  # $Id$
please remove this SVN dropping too.

2024-10-10 22:03 UTC, evasnow1992 commented
Hi Greg, thank you for your feedback. We've updated the scripts to address the issues you raised, including cleaning up stale comments, improving input data type handling, and updating the test expectation in UnitTestButina.py. We've pushed the updated changes to this PR. Please let us know if you have any further suggestions or revisions.

2024-10-11 03:01 UTC, greglandrum commented
@evasnow1992 the changes look good, thanks.
I see that you've marked this as draft. do you plan further changes?

2024-10-11 04:19 UTC, evasnow1992 commented
Hi Greg, thank you for the quick reply. I had marked this as a draft as I was waiting for all the tests to complete. No further changes are planned. Please let me know if you feel it's ready for merging or any further revision is needed.

2024-10-11 04:43 UTC, greglandrum approved these changes
LGTM

2024-10-11 04:44 UTC, merged

2024-10-11 04:44 UTC, greglandrum commented
Thanks for the contribution @evasnow1992 !