Fix some minor issues reported by ubsan and the compiler
rdkit/rdkit pull request #8015
Opened 2024-11-17 19:00 UTC by ricrogz

- `Code/DataStructs/Wrap/SparseIntVect.cpp` and `Code/GraphMol/Substruct/test1.cpp`: fix several build waringings about "possibly dangling reference to a temporary".

- `Code/GraphMol/CIPLabeler/rules/Pairlist.h` and `Code/GraphMol/CIPLabeler/catch_tests.cpp`: increase the size of `d_pairing`, as it overflowed when running `pyCIPLabelsValidation`.

- `Code/GraphMol/ChemReactions/MDLParser.cpp`: initialize chiralityPossible, which was passed as a reference to an uninitialized value to `ParseV3000CTAB()` and `finishMolProcessing()` (it would be assigned a value in `ParseV3000CTAB()`).

- `Code/GraphMol/MarvinParse/MarvinParser.cpp`: Fix downcasting `MarvinMolBase` `res` to `MarvinMol`.

- `Code/RDGeneral/testDict.cpp`:  fix some integer overflow issues.

2024-11-19 03:48 UTC, greglandrum requested changes
minor suggestions: consistent naming and fixing a typo

2024-11-19 03:48 UTC, greglandrum commented on Code/RDGeneral/testDict.cpp
> +  // than this will cause and overflow of std::any_cast<int>(*v)
```suggestion
  // than this will cause an overflow of std::any_cast<int>(*v)
```

2024-11-19 03:48 UTC, greglandrum commented on Code/GraphMol/CIPLabeler/rules/Pairlist.h
> +  static constexpr int pairing_nbits = sizeof(pairing_t) * 8;
```suggestion
  static constexpr int numPairingBits = sizeof(pairing_t) * 8;
```

2024-11-19 03:48 UTC, greglandrum commented on Code/GraphMol/CIPLabeler/rules/Pairlist.h
> +                   << (pairing_nbits - 1 - d_descriptors.size());
```suggestion
                   << (numPairingBits - 1 - d_descriptors.size());
```

2024-11-19 13:20 UTC, ricrogz commented
All suggestions accepted :)

2024-11-19 16:07 UTC, greglandrum commented
> All suggestions accepted :)

Thanks! Unfortunately there's at least one unchanged name that's breaking the builds

2024-11-20 08:03 UTC, greglandrum approved these changes
LGTM

2024-11-20 08:09 UTC, merged