Handle DOS files in SynthonSpaceSearch
rdkit/rdkit pull request #8075
Opened 2024-12-07 14:25 UTC by DavidACosgrove

#### Reference Issue
No issue but Igor from Enamine mentioned it was a problem.

#### What does this implement/fix? Explain your changes.
Uses the RDKit getLine() rather than std::get line() which handles CRLF.

#### Any other comments?
I think the test is problematic as the newlines are fixed on git checkout, at least on my Ubuntu development area.

2024-12-07 15:29 UTC, bp-kelley commented
In .gitattribute you can control line endings:

path/to/my/file eol=crlf

2024-12-08 05:40 UTC, greglandrum requested changes
The code changes look good, but please use a shorter test file. We don't need to add another long-running test for this one.

2024-12-09 13:31 UTC, greglandrum commented on Code/GraphMol/SynthonSpaceSearch/substructure_search_catch_tests.cpp
> +  std::cout << "num prods : " << synthonspace.getNumProducts() << std::endl;
Last suggested change, please remove this.
```suggestion
```

2024-12-09 13:32 UTC, greglandrum commented on Code/GraphMol/SynthonSpaceSearch/substructure_search_catch_tests.cpp
> +  std::cout << "num prods : " << synthonspace.getNumProducts() << std::endl;
actually, I can do that

2024-12-09 13:32 UTC, greglandrum approved these changes
LGTM
will merge after the CI builds pass

2024-12-09 16:29 UTC, merged